{
  "R": {
    "Version": "4.4.0",
    "Repositories": [
      {
        "Name": "BioCsoft",
        "URL": "https://bioconductor.org/packages/3.19/bioc"
      },
      {
        "Name": "BioCann",
        "URL": "https://bioconductor.org/packages/3.19/data/annotation"
      },
      {
        "Name": "BioCexp",
        "URL": "https://bioconductor.org/packages/3.19/data/experiment"
      },
      {
        "Name": "BioCworkflows",
        "URL": "https://bioconductor.org/packages/3.19/workflows"
      },
      {
        "Name": "BioCbooks",
        "URL": "https://bioconductor.org/packages/3.19/books"
      },
      {
        "Name": "CRAN",
        "URL": "https://cran.rstudio.com"
      }
    ]
  },
  "Bioconductor": {
    "Version": "3.19"
  },
  "Packages": {
    "AnnotationDbi": {
      "Package": "AnnotationDbi",
      "Version": "1.66.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "Biobase",
        "BiocGenerics",
        "DBI",
        "IRanges",
        "KEGGREST",
        "R",
        "RSQLite",
        "S4Vectors",
        "methods",
        "stats",
        "stats4"
      ],
      "Hash": "b7df9c597fb5533fc8248d73b8c703ac"
    },
    "AnnotationFilter": {
      "Package": "AnnotationFilter",
      "Version": "1.28.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "GenomicRanges",
        "R",
        "lazyeval",
        "methods",
        "utils"
      ],
      "Hash": "24e809470aef6d81b25003d775b2fb56"
    },
    "AnnotationHub": {
      "Package": "AnnotationHub",
      "Version": "3.12.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "AnnotationDbi",
        "BiocFileCache",
        "BiocGenerics",
        "BiocManager",
        "BiocVersion",
        "RSQLite",
        "S4Vectors",
        "curl",
        "dplyr",
        "grDevices",
        "httr",
        "methods",
        "rappdirs",
        "utils",
        "yaml"
      ],
      "Hash": "346ca347b61989d1da5f655d7bac6a8c"
    },
    "AsioHeaders": {
      "Package": "AsioHeaders",
      "Version": "1.22.1-2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "85bf3bd8fa58da21a22d84fd4f4ef0a8"
    },
    "BH": {
      "Package": "BH",
      "Version": "1.84.0-0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "a8235afbcd6316e6e91433ea47661013"
    },
    "Biobase": {
      "Package": "Biobase",
      "Version": "2.64.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "R",
        "methods",
        "utils"
      ],
      "Hash": "9bc4cabd3bfda461409172213d932813"
    },
    "BiocFileCache": {
      "Package": "BiocFileCache",
      "Version": "2.12.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "DBI",
        "R",
        "RSQLite",
        "curl",
        "dbplyr",
        "dplyr",
        "filelock",
        "httr",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "9c3414bcfae204d56080dd0f0a220136"
    },
    "BiocGenerics": {
      "Package": "BiocGenerics",
      "Version": "0.50.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "R",
        "graphics",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "ef32d07aafdd12f24c5827374ae3590d"
    },
    "BiocIO": {
      "Package": "BiocIO",
      "Version": "1.14.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "R",
        "S4Vectors",
        "methods",
        "tools"
      ],
      "Hash": "f97a7ef01d364cf20d1946d43a3d526f"
    },
    "BiocManager": {
      "Package": "BiocManager",
      "Version": "1.30.23",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "utils"
      ],
      "Hash": "47e968dfe563c1b22c2e20a067ec21d5"
    },
    "BiocNeighbors": {
      "Package": "BiocNeighbors",
      "Version": "1.22.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocParallel",
        "Matrix",
        "Rcpp",
        "RcppHNSW",
        "S4Vectors",
        "methods",
        "stats"
      ],
      "Hash": "da9f332c88453734623406dcca13ee03"
    },
    "BiocParallel": {
      "Package": "BiocParallel",
      "Version": "1.38.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BH",
        "R",
        "codetools",
        "cpp11",
        "futile.logger",
        "methods",
        "parallel",
        "snow",
        "stats",
        "utils"
      ],
      "Hash": "7b6e79f86e3d1c23f62c5e2052e848d4"
    },
    "BiocSingular": {
      "Package": "BiocSingular",
      "Version": "1.20.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "BiocParallel",
        "DelayedArray",
        "Matrix",
        "Rcpp",
        "S4Vectors",
        "ScaledMatrix",
        "beachmat",
        "irlba",
        "methods",
        "rsvd",
        "utils"
      ],
      "Hash": "9d2e9fbd803f4eddfeb307b1ee376aad"
    },
    "BiocVersion": {
      "Package": "BiocVersion",
      "Version": "3.19.1",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "R"
      ],
      "Hash": "b892e27fc9659a4c8f8787d34c37b8b2"
    },
    "Biostrings": {
      "Package": "Biostrings",
      "Version": "2.72.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "GenomeInfoDb",
        "IRanges",
        "R",
        "S4Vectors",
        "XVector",
        "crayon",
        "grDevices",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "48618c7c7b90b503837824ebcfee6363"
    },
    "Cairo": {
      "Package": "Cairo",
      "Version": "1.6-2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "graphics"
      ],
      "Hash": "3918e6b40d27984ca4a99c73b92406c3"
    },
    "DBI": {
      "Package": "DBI",
      "Version": "1.2.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "methods"
      ],
      "Hash": "164809cd72e1d5160b4cb3aa57f510fe"
    },
    "DEoptimR": {
      "Package": "DEoptimR",
      "Version": "1.1-3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "stats"
      ],
      "Hash": "72f87e0092e39384aee16df8d67d7410"
    },
    "DT": {
      "Package": "DT",
      "Version": "0.33",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "crosstalk",
        "htmltools",
        "htmlwidgets",
        "httpuv",
        "jquerylib",
        "jsonlite",
        "magrittr",
        "promises"
      ],
      "Hash": "64ff3427f559ce3f2597a4fe13255cb6"
    },
    "DWLS": {
      "Package": "DWLS",
      "Version": "0.1.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "MAST",
        "R",
        "ROCR",
        "Seurat",
        "SummarizedExperiment",
        "dplyr",
        "e1071",
        "quadprog",
        "reshape",
        "stats",
        "utils",
        "varhandle"
      ],
      "Hash": "8e12d31fb16f7eb8d86d315c5c1d8dd2"
    },
    "DelayedArray": {
      "Package": "DelayedArray",
      "Version": "0.30.1",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "IRanges",
        "Matrix",
        "MatrixGenerics",
        "R",
        "S4Arrays",
        "S4Vectors",
        "SparseArray",
        "methods",
        "stats",
        "stats4"
      ],
      "Hash": "395472c65cd9d606a1a345687102f299"
    },
    "DelayedMatrixStats": {
      "Package": "DelayedMatrixStats",
      "Version": "1.26.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "DelayedArray",
        "IRanges",
        "Matrix",
        "MatrixGenerics",
        "S4Vectors",
        "methods",
        "sparseMatrixStats"
      ],
      "Hash": "5d9536664ccddb0eaa68a90afe4ee76e"
    },
    "DropletUtils": {
      "Package": "DropletUtils",
      "Version": "1.24.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BH",
        "BiocGenerics",
        "BiocParallel",
        "DelayedArray",
        "DelayedMatrixStats",
        "GenomicRanges",
        "HDF5Array",
        "IRanges",
        "Matrix",
        "R.utils",
        "Rcpp",
        "Rhdf5lib",
        "S4Vectors",
        "SingleCellExperiment",
        "SummarizedExperiment",
        "beachmat",
        "dqrng",
        "edgeR",
        "methods",
        "rhdf5",
        "scuttle",
        "stats",
        "utils"
      ],
      "Hash": "77f762ad74d48a0ef578fc81deded039"
    },
    "EpiDISH": {
      "Package": "EpiDISH",
      "Version": "2.20.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "MASS",
        "Matrix",
        "R",
        "e1071",
        "locfdr",
        "matrixStats",
        "parallel",
        "quadprog",
        "stats",
        "stringr"
      ],
      "Hash": "e98ef0cd98b1ca994c2e66da5065c480"
    },
    "ExperimentHub": {
      "Package": "ExperimentHub",
      "Version": "2.12.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "AnnotationHub",
        "BiocFileCache",
        "BiocGenerics",
        "BiocManager",
        "S4Vectors",
        "methods",
        "rappdirs",
        "utils"
      ],
      "Hash": "988693270e5886a33c536dda6b3c9f98"
    },
    "FNN": {
      "Package": "FNN",
      "Version": "1.1.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "eaabdc7938aa3632a28273f53a0d226d"
    },
    "GEOquery": {
      "Package": "GEOquery",
      "Version": "2.72.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "Biobase",
        "R.utils",
        "curl",
        "data.table",
        "dplyr",
        "limma",
        "magrittr",
        "methods",
        "readr",
        "tidyr",
        "xml2"
      ],
      "Hash": "b27b8e249f59da9349a482311c603a58"
    },
    "GGally": {
      "Package": "GGally",
      "Version": "2.2.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "RColorBrewer",
        "dplyr",
        "ggplot2",
        "ggstats",
        "grDevices",
        "grid",
        "gtable",
        "lifecycle",
        "magrittr",
        "plyr",
        "progress",
        "rlang",
        "scales",
        "tidyr",
        "utils"
      ],
      "Hash": "b11ac45c916608b7d1374ff87da053d5"
    },
    "GO.db": {
      "Package": "GO.db",
      "Version": "3.19.1",
      "Source": "Bioconductor",
      "Requirements": [
        "AnnotationDbi",
        "R",
        "methods"
      ],
      "Hash": "46bfc38370acea3503c223347915e43b"
    },
    "GenomeInfoDb": {
      "Package": "GenomeInfoDb",
      "Version": "1.40.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "GenomeInfoDbData",
        "IRanges",
        "R",
        "S4Vectors",
        "UCSC.utils",
        "methods",
        "stats",
        "stats4",
        "utils"
      ],
      "Hash": "614124bc9fb80d222cfa0d2e3e76c339"
    },
    "GenomeInfoDbData": {
      "Package": "GenomeInfoDbData",
      "Version": "1.2.12",
      "Source": "Bioconductor",
      "Requirements": [
        "R"
      ],
      "Hash": "c3c792a7b7f2677be56e8632c5b7543d"
    },
    "GenomicAlignments": {
      "Package": "GenomicAlignments",
      "Version": "1.40.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "BiocParallel",
        "Biostrings",
        "GenomeInfoDb",
        "GenomicRanges",
        "IRanges",
        "R",
        "Rsamtools",
        "S4Vectors",
        "SummarizedExperiment",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "e539709764587c581b31e446dc84d7b8"
    },
    "GenomicFeatures": {
      "Package": "GenomicFeatures",
      "Version": "1.56.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "AnnotationDbi",
        "BiocGenerics",
        "Biostrings",
        "DBI",
        "GenomeInfoDb",
        "GenomicRanges",
        "IRanges",
        "R",
        "S4Vectors",
        "XVector",
        "methods",
        "rtracklayer",
        "stats",
        "utils"
      ],
      "Hash": "0d19619d13b06b9dea85993ce7f09c52"
    },
    "GenomicRanges": {
      "Package": "GenomicRanges",
      "Version": "1.56.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "GenomeInfoDb",
        "IRanges",
        "R",
        "S4Vectors",
        "XVector",
        "methods",
        "stats",
        "stats4",
        "utils"
      ],
      "Hash": "0fab423e3f49e207681eb404d9182a1e"
    },
    "HDF5Array": {
      "Package": "HDF5Array",
      "Version": "1.32.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "DelayedArray",
        "IRanges",
        "Matrix",
        "R",
        "Rhdf5lib",
        "S4Arrays",
        "S4Vectors",
        "methods",
        "rhdf5",
        "rhdf5filters",
        "stats",
        "tools",
        "utils"
      ],
      "Hash": "b10ddb24baf506cf7b4bc868ae65b984"
    },
    "IRanges": {
      "Package": "IRanges",
      "Version": "2.38.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "R",
        "S4Vectors",
        "methods",
        "stats",
        "stats4",
        "utils"
      ],
      "Hash": "836770692f7c8401090519228b93af32"
    },
    "KEGGREST": {
      "Package": "KEGGREST",
      "Version": "1.44.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "Biostrings",
        "R",
        "httr",
        "methods",
        "png"
      ],
      "Hash": "05ef9fd9aa613310e060ddd93a0c8571"
    },
    "KernSmooth": {
      "Package": "KernSmooth",
      "Version": "2.23-24",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "stats"
      ],
      "Hash": "9f33a1ee37bbe8919eb2ec4b9f2473a5"
    },
    "MASS": {
      "Package": "MASS",
      "Version": "7.3-60.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "graphics",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "2f342c46163b0b54d7b64d1f798e2c78"
    },
    "MAST": {
      "Package": "MAST",
      "Version": "1.30.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "Biobase",
        "BiocGenerics",
        "Matrix",
        "R",
        "S4Vectors",
        "SingleCellExperiment",
        "SummarizedExperiment",
        "abind",
        "data.table",
        "ggplot2",
        "graphics",
        "methods",
        "parallel",
        "plyr",
        "progress",
        "reshape2",
        "stats",
        "stats4",
        "stringr",
        "utils"
      ],
      "Hash": "0346ae4687222cc5699296fe5245eecf"
    },
    "MCMCpack": {
      "Package": "MCMCpack",
      "Version": "1.7-0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "MASS",
        "R",
        "coda",
        "grDevices",
        "graphics",
        "lattice",
        "mcmc",
        "methods",
        "quantreg",
        "stats",
        "utils"
      ],
      "Hash": "225c857e115cf09e1804ff3e597fe555"
    },
    "Matrix": {
      "Package": "Matrix",
      "Version": "1.7-0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "graphics",
        "grid",
        "lattice",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "1920b2f11133b12350024297d8a4ff4a"
    },
    "MatrixGenerics": {
      "Package": "MatrixGenerics",
      "Version": "1.16.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "matrixStats",
        "methods"
      ],
      "Hash": "152dbbcde6a9a7c7f3beef79b68cd76a"
    },
    "MatrixModels": {
      "Package": "MatrixModels",
      "Version": "0.5-3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "R",
        "methods",
        "stats"
      ],
      "Hash": "0776bf7526869e0286b0463cb72fb211"
    },
    "MuSiC": {
      "Package": "MuSiC",
      "Version": "1.0.0",
      "Source": "GitHub",
      "Remotes": "",
      "RemoteType": "github",
      "RemoteHost": "api.github.com",
      "RemoteRepo": "MuSiC",
      "RemoteUsername": "xuranw",
      "RemoteRef": "HEAD",
      "RemoteSha": "f21fe67f5670d5e9fca0ad7550abaae3423eb59c",
      "Requirements": [
        "Biobase",
        "MCMCpack",
        "Matrix",
        "R",
        "SingleCellExperiment",
        "TOAST",
        "ggplot2",
        "nnls"
      ],
      "Hash": "987cd1c19f22346845d5017c7c3bcd3b"
    },
    "NCmisc": {
      "Package": "NCmisc",
      "Version": "1.2.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "graphics",
        "methods",
        "stats",
        "tools",
        "utils"
      ],
      "Hash": "57805bff69b9ca137e70fb83bf0e35f9"
    },
    "ProtGenerics": {
      "Package": "ProtGenerics",
      "Version": "1.36.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "methods"
      ],
      "Hash": "a3737c10efc865abfa9d204ca8735b74"
    },
    "R.methodsS3": {
      "Package": "R.methodsS3",
      "Version": "1.8.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "utils"
      ],
      "Hash": "278c286fd6e9e75d0c2e8f731ea445c8"
    },
    "R.oo": {
      "Package": "R.oo",
      "Version": "1.26.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R.methodsS3",
        "methods",
        "utils"
      ],
      "Hash": "4fed809e53ddb5407b3da3d0f572e591"
    },
    "R.utils": {
      "Package": "R.utils",
      "Version": "2.12.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R.methodsS3",
        "R.oo",
        "methods",
        "tools",
        "utils"
      ],
      "Hash": "3dc2829b790254bfba21e60965787651"
    },
    "R6": {
      "Package": "R6",
      "Version": "2.5.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "470851b6d5d0ac559e9d01bb352b4021"
    },
    "RANN": {
      "Package": "RANN",
      "Version": "2.6.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "d128ea05a972d3e67c6f39de52c72bd7"
    },
    "RApiSerialize": {
      "Package": "RApiSerialize",
      "Version": "0.1.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "12cbd319d03b55edaa195695a155bb30"
    },
    "RColorBrewer": {
      "Package": "RColorBrewer",
      "Version": "1.1-3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "45f0398006e83a5b10b72a90663d8d8c"
    },
    "RCurl": {
      "Package": "RCurl",
      "Version": "1.98-1.14",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "bitops",
        "methods"
      ],
      "Hash": "47f648d288079d0c696804ad4e55197e"
    },
    "ROCR": {
      "Package": "ROCR",
      "Version": "1.0-11",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "gplots",
        "grDevices",
        "graphics",
        "methods",
        "stats"
      ],
      "Hash": "cc151930e20e16427bc3d0daec62b4a9"
    },
    "RSQLite": {
      "Package": "RSQLite",
      "Version": "2.3.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "DBI",
        "R",
        "bit64",
        "blob",
        "cpp11",
        "memoise",
        "methods",
        "pkgconfig",
        "plogr",
        "rlang"
      ],
      "Hash": "ae4a925e0f6bb1b7e5fa96b739c5221a"
    },
    "RSpectra": {
      "Package": "RSpectra",
      "Version": "0.16-1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "R",
        "Rcpp",
        "RcppEigen"
      ],
      "Hash": "6b5ab997fd5ff6d46a5f1d9f8b76961c"
    },
    "Rcpp": {
      "Package": "Rcpp",
      "Version": "1.0.12",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "methods",
        "utils"
      ],
      "Hash": "5ea2700d21e038ace58269ecdbeb9ec0"
    },
    "RcppAnnoy": {
      "Package": "RcppAnnoy",
      "Version": "0.0.22",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "Rcpp",
        "methods"
      ],
      "Hash": "f6baa1e06fb6c3724f601a764266cb0d"
    },
    "RcppArmadillo": {
      "Package": "RcppArmadillo",
      "Version": "0.12.8.3.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "Rcpp",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "1eb4a0603478b5557b77d75534251371"
    },
    "RcppEigen": {
      "Package": "RcppEigen",
      "Version": "0.3.4.0.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "Rcpp",
        "stats",
        "utils"
      ],
      "Hash": "df49e3306f232ec28f1604e36a202847"
    },
    "RcppHNSW": {
      "Package": "RcppHNSW",
      "Version": "0.6.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Rcpp",
        "methods"
      ],
      "Hash": "1f2dc32c27746a35196aaf95adb357be"
    },
    "RcppML": {
      "Package": "RcppML",
      "Version": "0.3.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "Rcpp",
        "RcppEigen",
        "methods",
        "stats"
      ],
      "Hash": "225157373f361daf85198a8d1ddaa733"
    },
    "RcppParallel": {
      "Package": "RcppParallel",
      "Version": "5.1.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "a45594a00f5dbb073d5ec9f48592a08a"
    },
    "RcppProgress": {
      "Package": "RcppProgress",
      "Version": "0.4.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "1c0aa18b97e6aaa17f93b8b866c0ace5"
    },
    "RcppTOML": {
      "Package": "RcppTOML",
      "Version": "0.2.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "Rcpp"
      ],
      "Hash": "c232938949fcd8126034419cc529333a"
    },
    "ResidualMatrix": {
      "Package": "ResidualMatrix",
      "Version": "1.14.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "DelayedArray",
        "Matrix",
        "S4Vectors",
        "methods"
      ],
      "Hash": "26b5d104b2d27d7aa3725c4e3aa1b3b9"
    },
    "Rhdf5lib": {
      "Package": "Rhdf5lib",
      "Version": "1.26.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "R"
      ],
      "Hash": "c92ba8b9a2c5c9ff600a1062a3b7b727"
    },
    "RhpcBLASctl": {
      "Package": "RhpcBLASctl",
      "Version": "0.23-42",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "c966ea2957ff75e77afa5c908dfc89e1"
    },
    "Rhtslib": {
      "Package": "Rhtslib",
      "Version": "3.0.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "tools",
        "zlibbioc"
      ],
      "Hash": "5d6514cd44a0106581e3310f3972a82e"
    },
    "Rsamtools": {
      "Package": "Rsamtools",
      "Version": "2.20.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "BiocParallel",
        "Biostrings",
        "GenomeInfoDb",
        "GenomicRanges",
        "IRanges",
        "R",
        "Rhtslib",
        "S4Vectors",
        "XVector",
        "bitops",
        "methods",
        "stats",
        "utils",
        "zlibbioc"
      ],
      "Hash": "9762f24dcbdbd1626173c516bb64792c"
    },
    "Rtsne": {
      "Package": "Rtsne",
      "Version": "0.17",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Rcpp",
        "stats"
      ],
      "Hash": "f81f7764a3c3e310b1d40e1a8acee19e"
    },
    "S4Arrays": {
      "Package": "S4Arrays",
      "Version": "1.4.1",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "IRanges",
        "Matrix",
        "R",
        "S4Vectors",
        "abind",
        "crayon",
        "methods",
        "stats"
      ],
      "Hash": "deeed4802c5132e88f24a432a1caf5e0"
    },
    "S4Vectors": {
      "Package": "S4Vectors",
      "Version": "0.42.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "R",
        "methods",
        "stats",
        "stats4",
        "utils"
      ],
      "Hash": "245ac721ca6088200392ea5251db9e3c"
    },
    "SMVar": {
      "Package": "SMVar",
      "Version": "1.3.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "a7a827a889a4b1058d781e2834bef62c"
    },
    "ScaledMatrix": {
      "Package": "ScaledMatrix",
      "Version": "1.12.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "DelayedArray",
        "Matrix",
        "S4Vectors",
        "methods"
      ],
      "Hash": "bac1c808a92d9c3f45d05e7a8c1b74f0"
    },
    "Seurat": {
      "Package": "Seurat",
      "Version": "5.1.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "KernSmooth",
        "MASS",
        "Matrix",
        "R",
        "RANN",
        "RColorBrewer",
        "ROCR",
        "RSpectra",
        "Rcpp",
        "RcppAnnoy",
        "RcppEigen",
        "RcppHNSW",
        "RcppProgress",
        "Rtsne",
        "SeuratObject",
        "cluster",
        "cowplot",
        "fastDummies",
        "fitdistrplus",
        "future",
        "future.apply",
        "generics",
        "ggplot2",
        "ggrepel",
        "ggridges",
        "grDevices",
        "graphics",
        "grid",
        "httr",
        "ica",
        "igraph",
        "irlba",
        "jsonlite",
        "leiden",
        "lifecycle",
        "lmtest",
        "matrixStats",
        "methods",
        "miniUI",
        "patchwork",
        "pbapply",
        "plotly",
        "png",
        "progressr",
        "purrr",
        "reticulate",
        "rlang",
        "scales",
        "scattermore",
        "sctransform",
        "shiny",
        "spatstat.explore",
        "spatstat.geom",
        "stats",
        "tibble",
        "tools",
        "utils",
        "uwot"
      ],
      "Hash": "aa2040fec3d03e3e598e0b406a84a104"
    },
    "SeuratObject": {
      "Package": "SeuratObject",
      "Version": "5.0.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "R",
        "Rcpp",
        "RcppEigen",
        "future",
        "future.apply",
        "generics",
        "grDevices",
        "grid",
        "lifecycle",
        "methods",
        "progressr",
        "rlang",
        "sp",
        "spam",
        "stats",
        "tools",
        "utils"
      ],
      "Hash": "e9b70412b7e04571b46101f5dcbaacad"
    },
    "SingleCellExperiment": {
      "Package": "SingleCellExperiment",
      "Version": "1.26.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "DelayedArray",
        "GenomicRanges",
        "S4Vectors",
        "SummarizedExperiment",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "4476ad434a5e7887884521417cab3764"
    },
    "SingleR": {
      "Package": "SingleR",
      "Version": "2.6.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocNeighbors",
        "BiocParallel",
        "BiocSingular",
        "DelayedArray",
        "DelayedMatrixStats",
        "Matrix",
        "Rcpp",
        "S4Vectors",
        "SummarizedExperiment",
        "beachmat",
        "methods",
        "parallel",
        "stats",
        "utils"
      ],
      "Hash": "754516444a16b2616e35e9c8767d1110"
    },
    "SparseArray": {
      "Package": "SparseArray",
      "Version": "1.4.5",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "IRanges",
        "Matrix",
        "MatrixGenerics",
        "R",
        "S4Arrays",
        "S4Vectors",
        "XVector",
        "matrixStats",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "c3a929f64891a53c31f4b35c3d06a056"
    },
    "SparseM": {
      "Package": "SparseM",
      "Version": "1.81",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "graphics",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "2042cd9759cc89a453c4aefef0ce9aae"
    },
    "SummarizedExperiment": {
      "Package": "SummarizedExperiment",
      "Version": "1.34.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "Biobase",
        "BiocGenerics",
        "DelayedArray",
        "GenomeInfoDb",
        "GenomicRanges",
        "IRanges",
        "Matrix",
        "MatrixGenerics",
        "R",
        "S4Arrays",
        "S4Vectors",
        "methods",
        "stats",
        "tools",
        "utils"
      ],
      "Hash": "2f6c8cc972ed6aee07c96e3dff729d15"
    },
    "TOAST": {
      "Package": "TOAST",
      "Version": "1.18.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "EpiDISH",
        "GGally",
        "R",
        "SummarizedExperiment",
        "corpcor",
        "doParallel",
        "ggplot2",
        "limma",
        "methods",
        "nnls",
        "parallel",
        "quadprog",
        "stats",
        "tidyr"
      ],
      "Hash": "6c68cb4498d0397e3c13d536755b4963"
    },
    "TSP": {
      "Package": "TSP",
      "Version": "1.2-4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "foreach",
        "grDevices",
        "graphics",
        "stats",
        "utils"
      ],
      "Hash": "7fba3f587b0f3cb3232d03d540dbf772"
    },
    "UCSC.utils": {
      "Package": "UCSC.utils",
      "Version": "1.0.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "S4Vectors",
        "httr",
        "jsonlite",
        "methods",
        "stats"
      ],
      "Hash": "83d45b690bffd09d1980c224ef329f5b"
    },
    "V8": {
      "Package": "V8",
      "Version": "4.4.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Rcpp",
        "curl",
        "jsonlite",
        "utils"
      ],
      "Hash": "ca98390ad1cef2a5a609597b49d3d042"
    },
    "XML": {
      "Package": "XML",
      "Version": "3.99-0.16.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "methods",
        "utils"
      ],
      "Hash": "da3098169c887914551b607c66fe2a28"
    },
    "XVector": {
      "Package": "XVector",
      "Version": "0.44.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "IRanges",
        "R",
        "S4Vectors",
        "methods",
        "tools",
        "utils",
        "zlibbioc"
      ],
      "Hash": "4245b9938ac74c0dbddbebbec6036ab4"
    },
    "abind": {
      "Package": "abind",
      "Version": "1.4-5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "methods",
        "utils"
      ],
      "Hash": "4f57884290cc75ab22f4af9e9d4ca862"
    },
    "affxparser": {
      "Package": "affxparser",
      "Version": "1.76.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "R"
      ],
      "Hash": "b99de904a5e417dee4c2d46fb1eb59f6"
    },
    "affy": {
      "Package": "affy",
      "Version": "1.82.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "Biobase",
        "BiocGenerics",
        "BiocManager",
        "R",
        "affyio",
        "grDevices",
        "graphics",
        "methods",
        "preprocessCore",
        "stats",
        "utils",
        "zlibbioc"
      ],
      "Hash": "de30a31c7d837db23467d5cbfcf88de0"
    },
    "affyio": {
      "Package": "affyio",
      "Version": "1.74.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "R",
        "methods",
        "zlibbioc"
      ],
      "Hash": "88e77a7f8571a173db7d4f6d9bf46a64"
    },
    "alabaster.base": {
      "Package": "alabaster.base",
      "Version": "1.4.1",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "Rcpp",
        "Rhdf5lib",
        "S4Vectors",
        "alabaster.schemas",
        "jsonlite",
        "jsonvalidate",
        "methods",
        "rhdf5",
        "utils"
      ],
      "Hash": "a4208190d6be247ff0a9d020e0caf4f3"
    },
    "alabaster.matrix": {
      "Package": "alabaster.matrix",
      "Version": "1.4.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "DelayedArray",
        "HDF5Array",
        "Matrix",
        "Rcpp",
        "S4Arrays",
        "S4Vectors",
        "SparseArray",
        "alabaster.base",
        "methods",
        "rhdf5"
      ],
      "Hash": "22b09ff731438f649f7a6bfe25dccde1"
    },
    "alabaster.ranges": {
      "Package": "alabaster.ranges",
      "Version": "1.4.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "GenomeInfoDb",
        "GenomicRanges",
        "IRanges",
        "S4Vectors",
        "alabaster.base",
        "methods",
        "rhdf5"
      ],
      "Hash": "74b3fe9e2e18d0f10e25af0278f5452a"
    },
    "alabaster.schemas": {
      "Package": "alabaster.schemas",
      "Version": "1.4.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Hash": "e58b4124478c9f912c7c4a21d9adca6c"
    },
    "alabaster.se": {
      "Package": "alabaster.se",
      "Version": "1.4.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "GenomicRanges",
        "IRanges",
        "S4Vectors",
        "SummarizedExperiment",
        "alabaster.base",
        "alabaster.matrix",
        "alabaster.ranges",
        "jsonlite",
        "methods"
      ],
      "Hash": "507cafb86c69a5f04a5ad0eb7f05fcf1"
    },
    "annotate": {
      "Package": "annotate",
      "Version": "1.82.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "AnnotationDbi",
        "Biobase",
        "BiocGenerics",
        "DBI",
        "R",
        "XML",
        "graphics",
        "httr",
        "methods",
        "stats",
        "utils",
        "xtable"
      ],
      "Hash": "659c0a3bfad51dc798e4b4eb0f2cdedc"
    },
    "anytime": {
      "Package": "anytime",
      "Version": "0.3.9",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "BH",
        "R",
        "Rcpp"
      ],
      "Hash": "74a64813f17b492da9c6afda6b128e3d"
    },
    "askpass": {
      "Package": "askpass",
      "Version": "1.2.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "sys"
      ],
      "Hash": "cad6cf7f1d5f6e906700b9d3e718c796"
    },
    "backports": {
      "Package": "backports",
      "Version": "1.4.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "c39fbec8a30d23e721980b8afb31984c"
    },
    "base64enc": {
      "Package": "base64enc",
      "Version": "0.1-3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "543776ae6848fde2f48ff3816d0628bc"
    },
    "batchelor": {
      "Package": "batchelor",
      "Version": "1.20.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "BiocNeighbors",
        "BiocParallel",
        "BiocSingular",
        "DelayedArray",
        "DelayedMatrixStats",
        "Matrix",
        "Rcpp",
        "ResidualMatrix",
        "S4Vectors",
        "ScaledMatrix",
        "SingleCellExperiment",
        "SummarizedExperiment",
        "beachmat",
        "igraph",
        "methods",
        "scuttle",
        "stats",
        "utils"
      ],
      "Hash": "ec5dcf85cdf644b078d02deaf27a3bfd"
    },
    "beachmat": {
      "Package": "beachmat",
      "Version": "2.20.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "DelayedArray",
        "Matrix",
        "Rcpp",
        "SparseArray",
        "methods"
      ],
      "Hash": "10e94b1bce9070632a40c6b873f8b2d4"
    },
    "beeswarm": {
      "Package": "beeswarm",
      "Version": "0.4.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "grDevices",
        "graphics",
        "stats",
        "utils"
      ],
      "Hash": "0f4e9d8caa6feaa7e409ae6c30f2ca66"
    },
    "biomaRt": {
      "Package": "biomaRt",
      "Version": "2.60.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "AnnotationDbi",
        "BiocFileCache",
        "digest",
        "httr2",
        "methods",
        "progress",
        "rappdirs",
        "stringr",
        "utils",
        "xml2"
      ],
      "Hash": "8bce67ed479b1d54e1627598edd9db30"
    },
    "bit": {
      "Package": "bit",
      "Version": "4.0.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "d242abec29412ce988848d0294b208fd"
    },
    "bit64": {
      "Package": "bit64",
      "Version": "4.0.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "bit",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "9fe98599ca456d6552421db0d6772d8f"
    },
    "bitops": {
      "Package": "bitops",
      "Version": "1.0-7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "b7d8d8ee39869c18d8846a184dd8a1af"
    },
    "blob": {
      "Package": "blob",
      "Version": "1.2.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "methods",
        "rlang",
        "vctrs"
      ],
      "Hash": "40415719b5a479b87949f3aa0aee737c"
    },
    "bluster": {
      "Package": "bluster",
      "Version": "1.14.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocNeighbors",
        "BiocParallel",
        "Matrix",
        "Rcpp",
        "S4Vectors",
        "cluster",
        "igraph",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "ed9597168d850071aa9abbbef7be7204"
    },
    "brio": {
      "Package": "brio",
      "Version": "1.1.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "c1ee497a6d999947c2c224ae46799b1a"
    },
    "broom": {
      "Package": "broom",
      "Version": "1.0.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "backports",
        "dplyr",
        "generics",
        "glue",
        "lifecycle",
        "purrr",
        "rlang",
        "stringr",
        "tibble",
        "tidyr"
      ],
      "Hash": "a4652c36d1f8abfc3ddf4774f768c934"
    },
    "broom.helpers": {
      "Package": "broom.helpers",
      "Version": "1.15.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "broom",
        "cli",
        "dplyr",
        "labelled",
        "lifecycle",
        "purrr",
        "rlang",
        "stats",
        "stringr",
        "tibble",
        "tidyr"
      ],
      "Hash": "768cae43c3da698d6b11763777301e43"
    },
    "bslib": {
      "Package": "bslib",
      "Version": "0.7.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "base64enc",
        "cachem",
        "fastmap",
        "grDevices",
        "htmltools",
        "jquerylib",
        "jsonlite",
        "lifecycle",
        "memoise",
        "mime",
        "rlang",
        "sass"
      ],
      "Hash": "8644cc53f43828f19133548195d7e59e"
    },
    "caTools": {
      "Package": "caTools",
      "Version": "1.18.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "bitops"
      ],
      "Hash": "34d90fa5845004236b9eacafc51d07b2"
    },
    "cachem": {
      "Package": "cachem",
      "Version": "1.1.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "fastmap",
        "rlang"
      ],
      "Hash": "cd9a672193789068eb5a2aad65a0dedf"
    },
    "callr": {
      "Package": "callr",
      "Version": "3.7.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R6",
        "processx",
        "utils"
      ],
      "Hash": "d7e13f49c19103ece9e58ad2d83a7354"
    },
    "celldex": {
      "Package": "celldex",
      "Version": "1.14.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "AnnotationDbi",
        "AnnotationHub",
        "DBI",
        "DelayedArray",
        "DelayedMatrixStats",
        "ExperimentHub",
        "Matrix",
        "RSQLite",
        "S4Vectors",
        "SummarizedExperiment",
        "alabaster.base",
        "alabaster.matrix",
        "alabaster.se",
        "gypsum",
        "jsonlite",
        "methods",
        "utils"
      ],
      "Hash": "23893b3ebc5833e56319d1136a154531"
    },
    "cellranger": {
      "Package": "cellranger",
      "Version": "1.1.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "rematch",
        "tibble"
      ],
      "Hash": "f61dbaec772ccd2e17705c1e872e9e7c"
    },
    "checkmate": {
      "Package": "checkmate",
      "Version": "2.3.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "backports",
        "utils"
      ],
      "Hash": "c01cab1cb0f9125211a6fc99d540e315"
    },
    "chromote": {
      "Package": "chromote",
      "Version": "0.2.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R6",
        "curl",
        "fastmap",
        "jsonlite",
        "later",
        "magrittr",
        "processx",
        "promises",
        "rlang",
        "utils",
        "websocket"
      ],
      "Hash": "3cfaf9cbd331e07055acada321664e12"
    },
    "class": {
      "Package": "class",
      "Version": "7.3-22",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "MASS",
        "R",
        "stats",
        "utils"
      ],
      "Hash": "f91f6b29f38b8c280f2b9477787d4bb2"
    },
    "cli": {
      "Package": "cli",
      "Version": "3.6.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "utils"
      ],
      "Hash": "1216ac65ac55ec0058a6f75d7ca0fd52"
    },
    "clipr": {
      "Package": "clipr",
      "Version": "0.8.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "utils"
      ],
      "Hash": "3f038e5ac7f41d4ac41ce658c85e3042"
    },
    "cluster": {
      "Package": "cluster",
      "Version": "2.1.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "graphics",
        "stats",
        "utils"
      ],
      "Hash": "0aaa05204035dc43ea0004b9c76611dd"
    },
    "coda": {
      "Package": "coda",
      "Version": "0.19-4.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "lattice"
      ],
      "Hash": "af436915c590afc6fffc3ce3a5be1569"
    },
    "codetools": {
      "Package": "codetools",
      "Version": "0.2-20",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "61e097f35917d342622f21cdc79c256e"
    },
    "colorspace": {
      "Package": "colorspace",
      "Version": "2.1-0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "graphics",
        "methods",
        "stats"
      ],
      "Hash": "f20c47fd52fae58b4e377c37bb8c335b"
    },
    "commonmark": {
      "Package": "commonmark",
      "Version": "1.9.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "5d8225445acb167abf7797de48b2ee3c"
    },
    "corpcor": {
      "Package": "corpcor",
      "Version": "1.6.10",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "stats"
      ],
      "Hash": "17ebe3b6d75d09c5bab3891880b34237"
    },
    "cowplot": {
      "Package": "cowplot",
      "Version": "1.1.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "ggplot2",
        "grDevices",
        "grid",
        "gtable",
        "methods",
        "rlang",
        "scales"
      ],
      "Hash": "8ef2084dd7d28847b374e55440e4f8cb"
    },
    "cpp11": {
      "Package": "cpp11",
      "Version": "0.4.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "5a295d7d963cc5035284dcdbaf334f4e"
    },
    "crayon": {
      "Package": "crayon",
      "Version": "1.5.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "grDevices",
        "methods",
        "utils"
      ],
      "Hash": "e8a1e41acf02548751f45c718d55aa6a"
    },
    "crossmeta": {
      "Package": "crossmeta",
      "Version": "1.23.3",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteHost": "api.github.com",
      "RemoteRepo": "crossmeta",
      "RemoteUsername": "alexvpickering",
      "RemoteRef": "HEAD",
      "RemoteSha": "fbcdc350ea3b5ba9226ac7fc132f468604013c89",
      "Requirements": [
        "AnnotationDbi",
        "Biobase",
        "BiocGenerics",
        "BiocManager",
        "DBI",
        "DT",
        "GEOquery",
        "R",
        "RCurl",
        "RSQLite",
        "XML",
        "affxparser",
        "affy",
        "data.table",
        "edgeR",
        "fdrtool",
        "limma",
        "matrixStats",
        "metaMA",
        "methods",
        "miniUI",
        "reader",
        "readxl",
        "shiny",
        "shinyBS",
        "shinyWidgets",
        "shinyjs",
        "shinypanel",
        "stringr",
        "sva",
        "tibble"
      ],
      "Hash": "f9dd846c9f5b74ebeddf45a9dd75566a"
    },
    "crosstalk": {
      "Package": "crosstalk",
      "Version": "1.2.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R6",
        "htmltools",
        "jsonlite",
        "lazyeval"
      ],
      "Hash": "ab12c7b080a57475248a30f4db6298c0"
    },
    "curl": {
      "Package": "curl",
      "Version": "5.2.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "411ca2c03b1ce5f548345d2fc2685f7a"
    },
    "data.table": {
      "Package": "data.table",
      "Version": "1.15.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "methods"
      ],
      "Hash": "8ee9ac56ef633d0c7cab8b2ca87d683e"
    },
    "dbplyr": {
      "Package": "dbplyr",
      "Version": "2.5.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "DBI",
        "R",
        "R6",
        "blob",
        "cli",
        "dplyr",
        "glue",
        "lifecycle",
        "magrittr",
        "methods",
        "pillar",
        "purrr",
        "rlang",
        "tibble",
        "tidyr",
        "tidyselect",
        "utils",
        "vctrs",
        "withr"
      ],
      "Hash": "39b2e002522bfd258039ee4e889e0fd1"
    },
    "deldir": {
      "Package": "deldir",
      "Version": "2.0-4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "graphics"
      ],
      "Hash": "24754fce82729ff85317dd195b6646a8"
    },
    "desc": {
      "Package": "desc",
      "Version": "1.4.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R6",
        "cli",
        "utils"
      ],
      "Hash": "99b79fcbd6c4d1ce087f5c5c758b384f"
    },
    "diffobj": {
      "Package": "diffobj",
      "Version": "0.3.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "crayon",
        "methods",
        "stats",
        "tools",
        "utils"
      ],
      "Hash": "bcaa8b95f8d7d01a5dedfd959ce88ab8"
    },
    "digest": {
      "Package": "digest",
      "Version": "0.6.35",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "utils"
      ],
      "Hash": "698ece7ba5a4fa4559e3d537e7ec3d31"
    },
    "doParallel": {
      "Package": "doParallel",
      "Version": "1.0.17",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "foreach",
        "iterators",
        "parallel",
        "utils"
      ],
      "Hash": "451e5edf411987991ab6a5410c45011f"
    },
    "dotCall64": {
      "Package": "dotCall64",
      "Version": "1.1-1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "80f374ef8500fcdc5d84a0345b837227"
    },
    "dplyr": {
      "Package": "dplyr",
      "Version": "1.1.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R6",
        "cli",
        "generics",
        "glue",
        "lifecycle",
        "magrittr",
        "methods",
        "pillar",
        "rlang",
        "tibble",
        "tidyselect",
        "utils",
        "vctrs"
      ],
      "Hash": "fedd9d00c2944ff00a0e2696ccf048ec"
    },
    "dqrng": {
      "Package": "dqrng",
      "Version": "0.4.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "BH",
        "R",
        "Rcpp",
        "sitmo"
      ],
      "Hash": "b31198e6268008976689b196bf9d883f"
    },
    "dseqr.data": {
      "Package": "dseqr.data",
      "Version": "0.99.9",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteHost": "api.github.com",
      "RemoteRepo": "dseqr.data",
      "RemoteUsername": "hms-dbmi",
      "RemoteRef": "HEAD",
      "RemoteSha": "b91592a64723ead71693b88f33a80787ce2d7200",
      "Requirements": [
        "AnnotationDbi",
        "AnnotationHub",
        "R",
        "biomaRt",
        "dplyr",
        "ensembldb",
        "qs",
        "utils"
      ],
      "Hash": "a4b152b2996baf45660058e75157410f"
    },
    "dtangle": {
      "Package": "dtangle",
      "Version": "2.0.9",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "DEoptimR",
        "R"
      ],
      "Hash": "fe53d2ea110c7772eb382bf058190d66"
    },
    "e1071": {
      "Package": "e1071",
      "Version": "1.7-14",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "class",
        "grDevices",
        "graphics",
        "methods",
        "proxy",
        "stats",
        "utils"
      ],
      "Hash": "4ef372b716824753719a8a38b258442d"
    },
    "edgeR": {
      "Package": "edgeR",
      "Version": "4.2.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "R",
        "Rcpp",
        "graphics",
        "limma",
        "locfit",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "20783ecb7e7cea3f351e8b21153e3eb8"
    },
    "ensembldb": {
      "Package": "ensembldb",
      "Version": "2.28.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "AnnotationDbi",
        "AnnotationFilter",
        "Biobase",
        "BiocGenerics",
        "Biostrings",
        "DBI",
        "GenomeInfoDb",
        "GenomicFeatures",
        "GenomicRanges",
        "IRanges",
        "ProtGenerics",
        "R",
        "RSQLite",
        "Rsamtools",
        "S4Vectors",
        "curl",
        "methods",
        "rtracklayer"
      ],
      "Hash": "f9a5e52468ec832a839c012e15c41c15"
    },
    "evaluate": {
      "Package": "evaluate",
      "Version": "0.23",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "methods"
      ],
      "Hash": "daf4a1246be12c1fa8c7705a0935c1a0"
    },
    "fansi": {
      "Package": "fansi",
      "Version": "1.0.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "utils"
      ],
      "Hash": "962174cf2aeb5b9eea581522286a911f"
    },
    "farver": {
      "Package": "farver",
      "Version": "2.1.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "680887028577f3fa2a81e410ed0d6e42"
    },
    "fastDummies": {
      "Package": "fastDummies",
      "Version": "1.7.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "data.table",
        "stringr",
        "tibble"
      ],
      "Hash": "e0f9c0c051e0e8d89996d7f0c400539f"
    },
    "fastmap": {
      "Package": "fastmap",
      "Version": "1.2.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "aa5e1cd11c2d15497494c5292d7ffcc8"
    },
    "fdrtool": {
      "Package": "fdrtool",
      "Version": "1.2.17",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "graphics",
        "stats"
      ],
      "Hash": "9feeb4e7a484e663a52d7de89135591a"
    },
    "filelock": {
      "Package": "filelock",
      "Version": "1.0.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "192053c276525c8495ccfd523aa8f2d1"
    },
    "fitdistrplus": {
      "Package": "fitdistrplus",
      "Version": "1.1-11",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "MASS",
        "R",
        "grDevices",
        "methods",
        "stats",
        "survival"
      ],
      "Hash": "f40ef9686e85681a1ccbf33d9236aeb9"
    },
    "fontawesome": {
      "Package": "fontawesome",
      "Version": "0.5.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "htmltools",
        "rlang"
      ],
      "Hash": "c2efdd5f0bcd1ea861c2d4e2a883a67d"
    },
    "forcats": {
      "Package": "forcats",
      "Version": "1.0.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "cli",
        "glue",
        "lifecycle",
        "magrittr",
        "rlang",
        "tibble"
      ],
      "Hash": "1a0a9a3d5083d0d573c4214576f1e690"
    },
    "foreach": {
      "Package": "foreach",
      "Version": "1.5.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "codetools",
        "iterators",
        "utils"
      ],
      "Hash": "618609b42c9406731ead03adf5379850"
    },
    "formatR": {
      "Package": "formatR",
      "Version": "1.14",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "63cb26d12517c7863f5abb006c5e0f25"
    },
    "fs": {
      "Package": "fs",
      "Version": "1.6.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "methods"
      ],
      "Hash": "15aeb8c27f5ea5161f9f6a641fafd93a"
    },
    "futile.logger": {
      "Package": "futile.logger",
      "Version": "1.4.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "futile.options",
        "lambda.r",
        "utils"
      ],
      "Hash": "99f0ace8c05ec7d3683d27083c4f1e7e"
    },
    "futile.options": {
      "Package": "futile.options",
      "Version": "1.0.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "0d9bf02413ddc2bbe8da9ce369dcdd2b"
    },
    "future": {
      "Package": "future",
      "Version": "1.33.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "digest",
        "globals",
        "listenv",
        "parallel",
        "parallelly",
        "utils"
      ],
      "Hash": "fd7b1d69d16d0d114e4fa82db68f184c"
    },
    "future.apply": {
      "Package": "future.apply",
      "Version": "1.11.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "future",
        "globals",
        "parallel",
        "utils"
      ],
      "Hash": "afe1507511629f44572e6c53b9baeb7c"
    },
    "genefilter": {
      "Package": "genefilter",
      "Version": "1.86.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "AnnotationDbi",
        "Biobase",
        "MatrixGenerics",
        "annotate",
        "grDevices",
        "graphics",
        "methods",
        "stats",
        "survival"
      ],
      "Hash": "a9954c24f8fbd7edce1dcf77c510b401"
    },
    "generics": {
      "Package": "generics",
      "Version": "0.1.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "methods"
      ],
      "Hash": "15e9634c0fcd294799e9b2e929ed1b86"
    },
    "ggbeeswarm": {
      "Package": "ggbeeswarm",
      "Version": "0.7.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "beeswarm",
        "cli",
        "ggplot2",
        "lifecycle",
        "vipor"
      ],
      "Hash": "899f28fe0388b7f687d7453429c2474d"
    },
    "ggplot2": {
      "Package": "ggplot2",
      "Version": "3.5.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "MASS",
        "R",
        "cli",
        "glue",
        "grDevices",
        "grid",
        "gtable",
        "isoband",
        "lifecycle",
        "mgcv",
        "rlang",
        "scales",
        "stats",
        "tibble",
        "vctrs",
        "withr"
      ],
      "Hash": "44c6a2f8202d5b7e878ea274b1092426"
    },
    "ggrastr": {
      "Package": "ggrastr",
      "Version": "1.0.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Cairo",
        "R",
        "ggbeeswarm",
        "ggplot2",
        "grid",
        "png",
        "ragg"
      ],
      "Hash": "7c8178842114bfcd44e688e7fd84c52a"
    },
    "ggrepel": {
      "Package": "ggrepel",
      "Version": "0.9.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "Rcpp",
        "ggplot2",
        "grid",
        "rlang",
        "scales",
        "withr"
      ],
      "Hash": "cc3361e234c4a5050e29697d675764aa"
    },
    "ggridges": {
      "Package": "ggridges",
      "Version": "0.5.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "ggplot2",
        "grid",
        "scales",
        "withr"
      ],
      "Hash": "66488692cb8621bc78df1b9b819497a6"
    },
    "ggstats": {
      "Package": "ggstats",
      "Version": "0.6.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "broom.helpers",
        "cli",
        "dplyr",
        "forcats",
        "ggplot2",
        "lifecycle",
        "magrittr",
        "patchwork",
        "purrr",
        "rlang",
        "scales",
        "stats",
        "stringr",
        "tidyr"
      ],
      "Hash": "02cdab34154e9e70dac279afbb20d34b"
    },
    "globals": {
      "Package": "globals",
      "Version": "0.16.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "codetools"
      ],
      "Hash": "2580567908cafd4f187c1e5a91e98b7f"
    },
    "glue": {
      "Package": "glue",
      "Version": "1.7.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "methods"
      ],
      "Hash": "e0b3a53876554bd45879e596cdb10a52"
    },
    "goftest": {
      "Package": "goftest",
      "Version": "1.2-3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "stats"
      ],
      "Hash": "dbe0201f91eeb15918dd3fbf01ee689a"
    },
    "gplots": {
      "Package": "gplots",
      "Version": "3.1.3.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "KernSmooth",
        "R",
        "caTools",
        "gtools",
        "methods",
        "stats"
      ],
      "Hash": "f72b5d1ed587f8905e38ee7295e88d80"
    },
    "gridExtra": {
      "Package": "gridExtra",
      "Version": "2.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "grDevices",
        "graphics",
        "grid",
        "gtable",
        "utils"
      ],
      "Hash": "7d7f283939f563670a697165b2cf5560"
    },
    "grr": {
      "Package": "grr",
      "Version": "0.9.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "195f3206842ea5ae11968e8d462bb828"
    },
    "gtable": {
      "Package": "gtable",
      "Version": "0.3.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "cli",
        "glue",
        "grid",
        "lifecycle",
        "rlang"
      ],
      "Hash": "e18861963cbc65a27736e02b3cd3c4a0"
    },
    "gtools": {
      "Package": "gtools",
      "Version": "3.9.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "588d091c35389f1f4a9d533c8d709b35"
    },
    "gypsum": {
      "Package": "gypsum",
      "Version": "1.0.1",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "filelock",
        "httr2",
        "jsonlite",
        "parallel",
        "tools",
        "utils"
      ],
      "Hash": "be467835669119ada5955d1d783488bd"
    },
    "harmony": {
      "Package": "harmony",
      "Version": "1.2.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "R",
        "Rcpp",
        "RcppArmadillo",
        "RcppProgress",
        "RhpcBLASctl",
        "cowplot",
        "dplyr",
        "ggplot2",
        "methods",
        "rlang",
        "tibble"
      ],
      "Hash": "4f3b181961712ff4127a8634c1367f89"
    },
    "haven": {
      "Package": "haven",
      "Version": "2.5.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "cli",
        "cpp11",
        "forcats",
        "hms",
        "lifecycle",
        "methods",
        "readr",
        "rlang",
        "tibble",
        "tidyselect",
        "vctrs"
      ],
      "Hash": "9171f898db9d9c4c1b2c745adc2c1ef1"
    },
    "hdf5r": {
      "Package": "hdf5r",
      "Version": "1.3.10",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R6",
        "bit64",
        "methods",
        "utils"
      ],
      "Hash": "455082f1cd7e02855a5bd087527706b5"
    },
    "here": {
      "Package": "here",
      "Version": "1.0.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "rprojroot"
      ],
      "Hash": "24b224366f9c2e7534d2344d10d59211"
    },
    "highr": {
      "Package": "highr",
      "Version": "0.10",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "xfun"
      ],
      "Hash": "06230136b2d2b9ba5805e1963fa6e890"
    },
    "hms": {
      "Package": "hms",
      "Version": "1.1.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "lifecycle",
        "methods",
        "pkgconfig",
        "rlang",
        "vctrs"
      ],
      "Hash": "b59377caa7ed00fa41808342002138f9"
    },
    "htmltools": {
      "Package": "htmltools",
      "Version": "0.5.8.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "base64enc",
        "digest",
        "fastmap",
        "grDevices",
        "rlang",
        "utils"
      ],
      "Hash": "81d371a9cc60640e74e4ab6ac46dcedc"
    },
    "htmlwidgets": {
      "Package": "htmlwidgets",
      "Version": "1.6.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "grDevices",
        "htmltools",
        "jsonlite",
        "knitr",
        "rmarkdown",
        "yaml"
      ],
      "Hash": "04291cc45198225444a397606810ac37"
    },
    "httpuv": {
      "Package": "httpuv",
      "Version": "1.6.15",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R6",
        "Rcpp",
        "later",
        "promises",
        "utils"
      ],
      "Hash": "d55aa087c47a63ead0f6fc10f8fa1ee0"
    },
    "httr": {
      "Package": "httr",
      "Version": "1.4.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R6",
        "curl",
        "jsonlite",
        "mime",
        "openssl"
      ],
      "Hash": "ac107251d9d9fd72f0ca8049988f1d7f"
    },
    "httr2": {
      "Package": "httr2",
      "Version": "1.0.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R6",
        "cli",
        "curl",
        "glue",
        "lifecycle",
        "magrittr",
        "openssl",
        "rappdirs",
        "rlang",
        "vctrs",
        "withr"
      ],
      "Hash": "03d741c92fda96d98c3a3f22494e3b4a"
    },
    "ica": {
      "Package": "ica",
      "Version": "1.0-3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "d9b52ced14e24a0e69e228c20eb5eb27"
    },
    "igraph": {
      "Package": "igraph",
      "Version": "2.0.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "R",
        "cli",
        "cpp11",
        "grDevices",
        "graphics",
        "lifecycle",
        "magrittr",
        "methods",
        "pkgconfig",
        "rlang",
        "stats",
        "utils",
        "vctrs"
      ],
      "Hash": "c3b7d801d722e26e4cd888e042bf9af5"
    },
    "irlba": {
      "Package": "irlba",
      "Version": "2.3.5.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "R",
        "methods",
        "stats"
      ],
      "Hash": "acb06a47b732c6251afd16e19c3201ff"
    },
    "isoband": {
      "Package": "isoband",
      "Version": "0.2.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "grid",
        "utils"
      ],
      "Hash": "0080607b4a1a7b28979aecef976d8bc2"
    },
    "iterators": {
      "Package": "iterators",
      "Version": "1.0.14",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "utils"
      ],
      "Hash": "8954069286b4b2b0d023d1b288dce978"
    },
    "jquerylib": {
      "Package": "jquerylib",
      "Version": "0.1.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "htmltools"
      ],
      "Hash": "5aab57a3bd297eee1c1d862735972182"
    },
    "jsonlite": {
      "Package": "jsonlite",
      "Version": "1.8.8",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "methods"
      ],
      "Hash": "e1b9c55281c5adc4dd113652d9e26768"
    },
    "jsonvalidate": {
      "Package": "jsonvalidate",
      "Version": "1.3.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "V8"
      ],
      "Hash": "cdc2843ef7f44f157198bb99aea7552d"
    },
    "knitr": {
      "Package": "knitr",
      "Version": "1.46",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "evaluate",
        "highr",
        "methods",
        "tools",
        "xfun",
        "yaml"
      ],
      "Hash": "6e008ab1d696a5283c79765fa7b56b47"
    },
    "labeling": {
      "Package": "labeling",
      "Version": "0.4.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "graphics",
        "stats"
      ],
      "Hash": "b64ec208ac5bc1852b285f665d6368b3"
    },
    "labelled": {
      "Package": "labelled",
      "Version": "2.13.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "dplyr",
        "haven",
        "lifecycle",
        "rlang",
        "stringr",
        "tidyr",
        "tidyselect",
        "vctrs"
      ],
      "Hash": "ad4b6d757624221aec6220b8c78defeb"
    },
    "lambda.r": {
      "Package": "lambda.r",
      "Version": "1.2.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "formatR"
      ],
      "Hash": "b1e925c4b9ffeb901bacf812cbe9a6ad"
    },
    "later": {
      "Package": "later",
      "Version": "1.3.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Rcpp",
        "rlang"
      ],
      "Hash": "a3e051d405326b8b0012377434c62b37"
    },
    "lattice": {
      "Package": "lattice",
      "Version": "0.22-6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "graphics",
        "grid",
        "stats",
        "utils"
      ],
      "Hash": "cc5ac1ba4c238c7ca9fa6a87ca11a7e2"
    },
    "lazyeval": {
      "Package": "lazyeval",
      "Version": "0.2.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "d908914ae53b04d4c0c0fd72ecc35370"
    },
    "leiden": {
      "Package": "leiden",
      "Version": "0.4.3.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "igraph",
        "methods",
        "reticulate"
      ],
      "Hash": "b21c4ae2bb7935504c42bcdf749c04e6"
    },
    "lifecycle": {
      "Package": "lifecycle",
      "Version": "1.0.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "cli",
        "glue",
        "rlang"
      ],
      "Hash": "b8552d117e1b808b09a832f589b79035"
    },
    "limma": {
      "Package": "limma",
      "Version": "3.60.2",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "R",
        "grDevices",
        "graphics",
        "methods",
        "statmod",
        "stats",
        "utils"
      ],
      "Hash": "e50bcf846c8a9109a961d6058c9e5112"
    },
    "listenv": {
      "Package": "listenv",
      "Version": "0.9.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "e2fca3e12e4db979dccc6e519b10a7ee"
    },
    "lmtest": {
      "Package": "lmtest",
      "Version": "0.9-40",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "graphics",
        "stats",
        "zoo"
      ],
      "Hash": "c6fafa6cccb1e1dfe7f7d122efd6e6a7"
    },
    "locfdr": {
      "Package": "locfdr",
      "Version": "1.1-8",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "graphics",
        "splines",
        "stats"
      ],
      "Hash": "2698cbc879db321e87ee97aa5c9abacd"
    },
    "locfit": {
      "Package": "locfit",
      "Version": "1.5-9.9",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "lattice"
      ],
      "Hash": "3885127e04b35dafded049075057ad83"
    },
    "magrittr": {
      "Package": "magrittr",
      "Version": "2.0.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "7ce2733a9826b3aeb1775d56fd305472"
    },
    "maketools": {
      "Package": "maketools",
      "Version": "1.3.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "sys"
      ],
      "Hash": "d35bdda507dff6db5739fd53fb73e676"
    },
    "matrixStats": {
      "Package": "matrixStats",
      "Version": "1.3.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "4b3ea27a19d669c0405b38134d89a9d1"
    },
    "mcmc": {
      "Package": "mcmc",
      "Version": "0.9-8",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "stats"
      ],
      "Hash": "d96d8fc4c4682220c601d294d2bc387e"
    },
    "memoise": {
      "Package": "memoise",
      "Version": "2.0.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "cachem",
        "rlang"
      ],
      "Hash": "e2817ccf4a065c5d9d7f2cfbe7c1d78c"
    },
    "metaMA": {
      "Package": "metaMA",
      "Version": "3.1.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "SMVar",
        "limma"
      ],
      "Hash": "142ef3b3b6f9e21ddba8918f56758796"
    },
    "metapod": {
      "Package": "metapod",
      "Version": "1.12.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "Rcpp"
      ],
      "Hash": "026552a86c3aa0d92d4d8b12d80010cc"
    },
    "mgcv": {
      "Package": "mgcv",
      "Version": "1.9-1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "R",
        "graphics",
        "methods",
        "nlme",
        "splines",
        "stats",
        "utils"
      ],
      "Hash": "110ee9d83b496279960e162ac97764ce"
    },
    "mime": {
      "Package": "mime",
      "Version": "0.12",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "tools"
      ],
      "Hash": "18e9c28c1d3ca1560ce30658b22ce104"
    },
    "miniUI": {
      "Package": "miniUI",
      "Version": "0.1.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "htmltools",
        "shiny",
        "utils"
      ],
      "Hash": "fec5f52652d60615fdb3957b3d74324a"
    },
    "munsell": {
      "Package": "munsell",
      "Version": "0.5.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "colorspace",
        "methods"
      ],
      "Hash": "4fd8900853b746af55b81fda99da7695"
    },
    "nlme": {
      "Package": "nlme",
      "Version": "3.1-164",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "graphics",
        "lattice",
        "stats",
        "utils"
      ],
      "Hash": "a623a2239e642806158bc4dc3f51565d"
    },
    "nnls": {
      "Package": "nnls",
      "Version": "1.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "942974f860268d8b22148d142bb8b946"
    },
    "openssl": {
      "Package": "openssl",
      "Version": "2.2.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "askpass"
      ],
      "Hash": "2bcca3848e4734eb3b16103bc9aa4b8e"
    },
    "parallelly": {
      "Package": "parallelly",
      "Version": "1.37.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "parallel",
        "tools",
        "utils"
      ],
      "Hash": "5410df8d22bd36e616f2a2343dbb328c"
    },
    "patchwork": {
      "Package": "patchwork",
      "Version": "1.2.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "cli",
        "ggplot2",
        "grDevices",
        "graphics",
        "grid",
        "gtable",
        "rlang",
        "stats",
        "utils"
      ],
      "Hash": "9c8ab14c00ac07e9e04d1664c0b74486"
    },
    "pbapply": {
      "Package": "pbapply",
      "Version": "1.7-2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "parallel"
      ],
      "Hash": "68a2d681e10cf72f0afa1d84d45380e5"
    },
    "pheatmap": {
      "Package": "pheatmap",
      "Version": "1.0.12",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "RColorBrewer",
        "grDevices",
        "graphics",
        "grid",
        "gtable",
        "scales",
        "stats"
      ],
      "Hash": "db1fb0021811b6693741325bbe916e58"
    },
    "picker": {
      "Package": "picker",
      "Version": "0.2.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "htmlwidgets"
      ],
      "Hash": "0b61270842cbb349406cff8ca4473bc5"
    },
    "pillar": {
      "Package": "pillar",
      "Version": "1.9.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "cli",
        "fansi",
        "glue",
        "lifecycle",
        "rlang",
        "utf8",
        "utils",
        "vctrs"
      ],
      "Hash": "15da5a8412f317beeee6175fbc76f4bb"
    },
    "pingr": {
      "Package": "pingr",
      "Version": "2.0.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "processx",
        "utils"
      ],
      "Hash": "8d2db1d13f4198a00ebf2f066bf2ab67"
    },
    "pkgbuild": {
      "Package": "pkgbuild",
      "Version": "1.4.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R6",
        "callr",
        "cli",
        "desc",
        "processx"
      ],
      "Hash": "a29e8e134a460a01e0ca67a4763c595b"
    },
    "pkgconfig": {
      "Package": "pkgconfig",
      "Version": "2.0.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "utils"
      ],
      "Hash": "01f28d4278f15c76cddbea05899c5d6f"
    },
    "pkgload": {
      "Package": "pkgload",
      "Version": "1.3.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "cli",
        "crayon",
        "desc",
        "fs",
        "glue",
        "methods",
        "pkgbuild",
        "rlang",
        "rprojroot",
        "utils",
        "withr"
      ],
      "Hash": "876c618df5ae610be84356d5d7a5d124"
    },
    "plogr": {
      "Package": "plogr",
      "Version": "0.2.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "09eb987710984fc2905c7129c7d85e65"
    },
    "plotly": {
      "Package": "plotly",
      "Version": "4.10.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "RColorBrewer",
        "base64enc",
        "crosstalk",
        "data.table",
        "digest",
        "dplyr",
        "ggplot2",
        "htmltools",
        "htmlwidgets",
        "httr",
        "jsonlite",
        "lazyeval",
        "magrittr",
        "promises",
        "purrr",
        "rlang",
        "scales",
        "tibble",
        "tidyr",
        "tools",
        "vctrs",
        "viridisLite"
      ],
      "Hash": "a1ac5c03ad5ad12b9d1597e00e23c3dd"
    },
    "plyr": {
      "Package": "plyr",
      "Version": "1.8.9",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "Rcpp"
      ],
      "Hash": "6b8177fd19982f0020743fadbfdbd933"
    },
    "png": {
      "Package": "png",
      "Version": "0.1-8",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "bd54ba8a0a5faded999a7aab6e46b374"
    },
    "polyclip": {
      "Package": "polyclip",
      "Version": "1.10-6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "436542aadb70675e361cf359285af7c7"
    },
    "praise": {
      "Package": "praise",
      "Version": "1.0.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "a555924add98c99d2f411e37e7d25e9f"
    },
    "preprocessCore": {
      "Package": "preprocessCore",
      "Version": "1.66.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "stats"
      ],
      "Hash": "d188d81b219bbf395f3281d3edb6328c"
    },
    "presto": {
      "Package": "presto",
      "Version": "1.0.0",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteHost": "api.github.com",
      "RemoteRepo": "presto",
      "RemoteUsername": "immunogenomics",
      "RemoteRef": "HEAD",
      "RemoteSha": "7636b3d0465c468c35853f82f1717d3a64b3c8f6",
      "Requirements": [
        "Matrix",
        "R",
        "Rcpp",
        "RcppArmadillo",
        "data.table",
        "dplyr",
        "methods",
        "purrr",
        "rlang",
        "stats",
        "tibble",
        "tidyr",
        "utils"
      ],
      "Hash": "c682f57757230a29913ad71f22aef990"
    },
    "prettyunits": {
      "Package": "prettyunits",
      "Version": "1.2.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "6b01fc98b1e86c4f705ce9dcfd2f57c7"
    },
    "processx": {
      "Package": "processx",
      "Version": "3.8.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R6",
        "ps",
        "utils"
      ],
      "Hash": "0c90a7d71988856bad2a2a45dd871bb9"
    },
    "progress": {
      "Package": "progress",
      "Version": "1.2.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R6",
        "crayon",
        "hms",
        "prettyunits"
      ],
      "Hash": "f4625e061cb2865f111b47ff163a5ca6"
    },
    "progressr": {
      "Package": "progressr",
      "Version": "0.14.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "digest",
        "utils"
      ],
      "Hash": "ac50c4ffa8f6a46580dd4d7813add3c4"
    },
    "promises": {
      "Package": "promises",
      "Version": "1.3.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R6",
        "Rcpp",
        "fastmap",
        "later",
        "magrittr",
        "rlang",
        "stats"
      ],
      "Hash": "434cd5388a3979e74be5c219bcd6e77d"
    },
    "proxy": {
      "Package": "proxy",
      "Version": "0.4-27",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "stats",
        "utils"
      ],
      "Hash": "e0ef355c12942cf7a6b91a6cfaea8b3e"
    },
    "ps": {
      "Package": "ps",
      "Version": "1.7.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "utils"
      ],
      "Hash": "dd2b9319ee0656c8acf45c7f40c59de7"
    },
    "purrr": {
      "Package": "purrr",
      "Version": "1.0.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "cli",
        "lifecycle",
        "magrittr",
        "rlang",
        "vctrs"
      ],
      "Hash": "1cba04a4e9414bdefc9dcaa99649a8dc"
    },
    "qs": {
      "Package": "qs",
      "Version": "0.26.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "BH",
        "R",
        "RApiSerialize",
        "Rcpp",
        "stringfish"
      ],
      "Hash": "e372cf3f70e3c7a768ec5ea14f0f3edd"
    },
    "quadprog": {
      "Package": "quadprog",
      "Version": "1.5-8",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "5f919ae5e7f83a6f91dcf2288943370d"
    },
    "quantreg": {
      "Package": "quantreg",
      "Version": "5.97",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "MASS",
        "Matrix",
        "MatrixModels",
        "R",
        "SparseM",
        "graphics",
        "methods",
        "stats",
        "survival"
      ],
      "Hash": "1bbc97f7d637ab3917c514a69047b2c1"
    },
    "ragg": {
      "Package": "ragg",
      "Version": "1.3.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "systemfonts",
        "textshaping"
      ],
      "Hash": "e3087db406e079a8a2fd87f413918ed3"
    },
    "rappdirs": {
      "Package": "rappdirs",
      "Version": "0.3.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "5e3c5dc0b071b21fa128676560dbe94d"
    },
    "rcmdcheck": {
      "Package": "rcmdcheck",
      "Version": "1.4.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R6",
        "callr",
        "cli",
        "curl",
        "desc",
        "digest",
        "pkgbuild",
        "prettyunits",
        "rprojroot",
        "sessioninfo",
        "utils",
        "withr",
        "xopen"
      ],
      "Hash": "8f25ebe2ec38b1f2aef3b0d2ef76f6c4"
    },
    "reader": {
      "Package": "reader",
      "Version": "1.0.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "NCmisc",
        "R",
        "grDevices",
        "graphics",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "ebf0939ae7cf7eb8776481430c279429"
    },
    "readr": {
      "Package": "readr",
      "Version": "2.1.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R6",
        "cli",
        "clipr",
        "cpp11",
        "crayon",
        "hms",
        "lifecycle",
        "methods",
        "rlang",
        "tibble",
        "tzdb",
        "utils",
        "vroom"
      ],
      "Hash": "9de96463d2117f6ac49980577939dfb3"
    },
    "readxl": {
      "Package": "readxl",
      "Version": "1.4.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "cellranger",
        "cpp11",
        "progress",
        "tibble",
        "utils"
      ],
      "Hash": "8cf9c239b96df1bbb133b74aef77ad0a"
    },
    "rematch": {
      "Package": "rematch",
      "Version": "2.0.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "cbff1b666c6fa6d21202f07e2318d4f1"
    },
    "rematch2": {
      "Package": "rematch2",
      "Version": "2.1.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "tibble"
      ],
      "Hash": "76c9e04c712a05848ae7a23d2f170a40"
    },
    "renv": {
      "Package": "renv",
      "Version": "1.0.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "utils"
      ],
      "Hash": "397b7b2a265bc5a7a06852524dabae20"
    },
    "repel": {
      "Package": "repel",
      "Version": "0.1",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteHost": "api.github.com",
      "RemoteRepo": "repel",
      "RemoteUsername": "hms-dbmi",
      "RemoteRef": "HEAD",
      "RemoteSha": "77394b17ba902d6b73d15d120557e43183c91527",
      "Requirements": [
        "R",
        "Rcpp",
        "grid",
        "rlang",
        "scales"
      ],
      "Hash": "c50167cbdc7a00815cc7ad905df143dd"
    },
    "reshape": {
      "Package": "reshape",
      "Version": "0.8.9",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "plyr"
      ],
      "Hash": "603d56041d7d4fa3ceb1864b3f6ee6b1"
    },
    "reshape2": {
      "Package": "reshape2",
      "Version": "1.4.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "Rcpp",
        "plyr",
        "stringr"
      ],
      "Hash": "bb5996d0bd962d214a11140d77589917"
    },
    "restfulr": {
      "Package": "restfulr",
      "Version": "0.0.15",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "RCurl",
        "S4Vectors",
        "XML",
        "methods",
        "rjson",
        "yaml"
      ],
      "Hash": "44651c1e68eda9d462610aca9f15a815"
    },
    "reticulate": {
      "Package": "reticulate",
      "Version": "1.37.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "R",
        "Rcpp",
        "RcppTOML",
        "graphics",
        "here",
        "jsonlite",
        "methods",
        "png",
        "rappdirs",
        "rlang",
        "utils",
        "withr"
      ],
      "Hash": "9465d3bc6ec44eeaa52527ac2cba4020"
    },
    "rhandsontable": {
      "Package": "rhandsontable",
      "Version": "0.3.8",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "htmlwidgets",
        "jsonlite",
        "magrittr",
        "methods",
        "utils"
      ],
      "Hash": "cc9b9fd1376181e84c88621711454676"
    },
    "rhdf5": {
      "Package": "rhdf5",
      "Version": "2.48.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "R",
        "Rhdf5lib",
        "methods",
        "rhdf5filters"
      ],
      "Hash": "74d8c5aeb96d090ce8efc9ffd16afa2b"
    },
    "rhdf5filters": {
      "Package": "rhdf5filters",
      "Version": "1.16.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "Rhdf5lib"
      ],
      "Hash": "99e15369f8fb17dc188377234de13fc6"
    },
    "rintrojs": {
      "Package": "rintrojs",
      "Version": "0.3.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "jsonlite",
        "shiny"
      ],
      "Hash": "e01800bef019328509364ab655fbcca6"
    },
    "rjson": {
      "Package": "rjson",
      "Version": "0.2.21",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "f9da75e6444e95a1baf8ca24909d63b9"
    },
    "rkal": {
      "Package": "rkal",
      "Version": "0.99.5",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteHost": "api.github.com",
      "RemoteRepo": "rkal",
      "RemoteUsername": "alexvpickering",
      "RemoteRef": "HEAD",
      "RemoteSha": "84836ce3a2538ef959f3cd8cd48b7bf5b0cf577b",
      "Requirements": [
        "Biobase",
        "DT",
        "R",
        "curl",
        "data.table",
        "dseqr.data",
        "edgeR",
        "miniUI",
        "rhdf5",
        "rlang",
        "shiny",
        "shinyjs",
        "tibble",
        "tximport",
        "utils"
      ],
      "Hash": "6e6025f2a9971ed2e9a6b5d62a076f33"
    },
    "rlang": {
      "Package": "rlang",
      "Version": "1.1.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "utils"
      ],
      "Hash": "42548638fae05fd9a9b5f3f437fbbbe2"
    },
    "rmarkdown": {
      "Package": "rmarkdown",
      "Version": "2.27",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "bslib",
        "evaluate",
        "fontawesome",
        "htmltools",
        "jquerylib",
        "jsonlite",
        "knitr",
        "methods",
        "tinytex",
        "tools",
        "utils",
        "xfun",
        "yaml"
      ],
      "Hash": "27f9502e1cdbfa195f94e03b0f517484"
    },
    "rprojroot": {
      "Package": "rprojroot",
      "Version": "2.0.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "4c8415e0ec1e29f3f4f6fc108bef0144"
    },
    "rsvd": {
      "Package": "rsvd",
      "Version": "1.0.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "R"
      ],
      "Hash": "b462187d887abc519894874486dbd6fd"
    },
    "rtracklayer": {
      "Package": "rtracklayer",
      "Version": "1.64.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "BiocIO",
        "Biostrings",
        "GenomeInfoDb",
        "GenomicAlignments",
        "GenomicRanges",
        "IRanges",
        "R",
        "Rsamtools",
        "S4Vectors",
        "XML",
        "XVector",
        "curl",
        "httr",
        "methods",
        "restfulr",
        "tools",
        "zlibbioc"
      ],
      "Hash": "3d6f004fce582bd7d68e2e18d44abbc1"
    },
    "sass": {
      "Package": "sass",
      "Version": "0.4.9",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R6",
        "fs",
        "htmltools",
        "rappdirs",
        "rlang"
      ],
      "Hash": "d53dbfddf695303ea4ad66f86e99b95d"
    },
    "scDblFinder": {
      "Package": "scDblFinder",
      "Version": "1.18.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "BiocNeighbors",
        "BiocParallel",
        "BiocSingular",
        "DelayedArray",
        "GenomeInfoDb",
        "GenomicRanges",
        "IRanges",
        "MASS",
        "Matrix",
        "R",
        "Rsamtools",
        "S4Vectors",
        "SingleCellExperiment",
        "SummarizedExperiment",
        "bluster",
        "igraph",
        "methods",
        "rtracklayer",
        "scater",
        "scran",
        "scuttle",
        "stats",
        "utils",
        "xgboost"
      ],
      "Hash": "3a998cfc42e06628628c320c904ffdaf"
    },
    "scales": {
      "Package": "scales",
      "Version": "1.3.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R6",
        "RColorBrewer",
        "cli",
        "farver",
        "glue",
        "labeling",
        "lifecycle",
        "munsell",
        "rlang",
        "viridisLite"
      ],
      "Hash": "c19df082ba346b0ffa6f833e92de34d1"
    },
    "scater": {
      "Package": "scater",
      "Version": "1.32.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "BiocNeighbors",
        "BiocParallel",
        "BiocSingular",
        "DelayedArray",
        "Matrix",
        "MatrixGenerics",
        "RColorBrewer",
        "RcppML",
        "Rtsne",
        "S4Vectors",
        "SingleCellExperiment",
        "SummarizedExperiment",
        "beachmat",
        "ggbeeswarm",
        "ggplot2",
        "ggrastr",
        "ggrepel",
        "methods",
        "pheatmap",
        "rlang",
        "scuttle",
        "stats",
        "utils",
        "uwot",
        "viridis"
      ],
      "Hash": "4a6eb8ab8a2b926fe67cf83aa731a3df"
    },
    "scattermore": {
      "Package": "scattermore",
      "Version": "1.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "ggplot2",
        "grDevices",
        "graphics",
        "grid",
        "scales"
      ],
      "Hash": "d316e4abb854dd1677f7bd3ad08bc4e8"
    },
    "scran": {
      "Package": "scran",
      "Version": "1.32.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BH",
        "BiocGenerics",
        "BiocParallel",
        "BiocSingular",
        "DelayedArray",
        "DelayedMatrixStats",
        "Matrix",
        "Rcpp",
        "S4Vectors",
        "SingleCellExperiment",
        "SummarizedExperiment",
        "beachmat",
        "bluster",
        "dqrng",
        "edgeR",
        "igraph",
        "limma",
        "metapod",
        "methods",
        "scuttle",
        "statmod",
        "stats",
        "utils"
      ],
      "Hash": "5b11173a6b49f06dda0db31e80caa561"
    },
    "sctransform": {
      "Package": "sctransform",
      "Version": "0.4.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "MASS",
        "Matrix",
        "R",
        "Rcpp",
        "RcppArmadillo",
        "dplyr",
        "future",
        "future.apply",
        "ggplot2",
        "gridExtra",
        "magrittr",
        "matrixStats",
        "methods",
        "reshape2",
        "rlang"
      ],
      "Hash": "0242402f321be0246fb67cf8c63b3572"
    },
    "scuttle": {
      "Package": "scuttle",
      "Version": "1.14.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocGenerics",
        "BiocParallel",
        "DelayedArray",
        "DelayedMatrixStats",
        "GenomicRanges",
        "Matrix",
        "Rcpp",
        "S4Vectors",
        "SingleCellExperiment",
        "SummarizedExperiment",
        "beachmat",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "6d94b72071aefd6e8b041c34ee83ebd0"
    },
    "sessioninfo": {
      "Package": "sessioninfo",
      "Version": "1.2.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "cli",
        "tools",
        "utils"
      ],
      "Hash": "3f9796a8d0a0e8c6eb49a4b029359d1f"
    },
    "shiny": {
      "Package": "shiny",
      "Version": "1.8.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R6",
        "bslib",
        "cachem",
        "commonmark",
        "crayon",
        "fastmap",
        "fontawesome",
        "glue",
        "grDevices",
        "htmltools",
        "httpuv",
        "jsonlite",
        "later",
        "lifecycle",
        "methods",
        "mime",
        "promises",
        "rlang",
        "sourcetools",
        "tools",
        "utils",
        "withr",
        "xtable"
      ],
      "Hash": "54b26646816af9960a4c64d8ceec75d6"
    },
    "shinyBS": {
      "Package": "shinyBS",
      "Version": "0.61.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "htmltools",
        "shiny"
      ],
      "Hash": "e44255f073ecdc26ba6bc2ce3fcf174d"
    },
    "shinyWidgets": {
      "Package": "shinyWidgets",
      "Version": "0.8.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "anytime",
        "bslib",
        "grDevices",
        "htmltools",
        "jsonlite",
        "rlang",
        "sass",
        "shiny"
      ],
      "Hash": "bc918b6911c4e928e24a9928295de834"
    },
    "shinydlplot": {
      "Package": "shinydlplot",
      "Version": "0.1.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "htmltools",
        "htmlwidgets",
        "methods",
        "plotly",
        "shiny",
        "shinyBS",
        "shinyjs",
        "utils"
      ],
      "Hash": "4bdc131718dedb1c32e649404660d044"
    },
    "shinyjs": {
      "Package": "shinyjs",
      "Version": "2.1.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "digest",
        "jsonlite",
        "shiny"
      ],
      "Hash": "802e4786b353a4bb27116957558548d5"
    },
    "shinypanel": {
      "Package": "shinypanel",
      "Version": "0.1.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "htmltools",
        "jsonlite",
        "shiny",
        "shinyBS",
        "shinyjs"
      ],
      "Hash": "433a3d71ce87d3b5ba11334dc94546db"
    },
    "shinytest2": {
      "Package": "shinytest2",
      "Version": "0.3.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R6",
        "callr",
        "checkmate",
        "chromote",
        "cpp11",
        "crayon",
        "fs",
        "globals",
        "httr",
        "jsonlite",
        "pingr",
        "rlang",
        "rmarkdown",
        "shiny",
        "testthat",
        "withr"
      ],
      "Hash": "a414c1bb2eb6e2a920742d3ebce84962"
    },
    "sitmo": {
      "Package": "sitmo",
      "Version": "2.0.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "Rcpp"
      ],
      "Hash": "c956d93f6768a9789edbc13072b70c78"
    },
    "snow": {
      "Package": "snow",
      "Version": "0.4-4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "utils"
      ],
      "Hash": "40b74690debd20c57d93d8c246b305d4"
    },
    "sourcetools": {
      "Package": "sourcetools",
      "Version": "0.1.7-1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "5f5a7629f956619d519205ec475fe647"
    },
    "sp": {
      "Package": "sp",
      "Version": "2.1-4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "graphics",
        "grid",
        "lattice",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "75940133cca2e339afce15a586f85b11"
    },
    "spam": {
      "Package": "spam",
      "Version": "2.10-0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "Rcpp",
        "dotCall64",
        "grid",
        "methods"
      ],
      "Hash": "ffe1f9e95a4375530747b268f82b5086"
    },
    "sparseMatrixStats": {
      "Package": "sparseMatrixStats",
      "Version": "1.16.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "Matrix",
        "MatrixGenerics",
        "Rcpp",
        "matrixStats",
        "methods"
      ],
      "Hash": "7e500a5a527460ca0406473bdcade286"
    },
    "spatstat.data": {
      "Package": "spatstat.data",
      "Version": "3.0-4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "R",
        "spatstat.utils"
      ],
      "Hash": "114a35341cb4955e1b8d30e28ec356c6"
    },
    "spatstat.explore": {
      "Package": "spatstat.explore",
      "Version": "3.2-7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "R",
        "abind",
        "goftest",
        "grDevices",
        "graphics",
        "methods",
        "nlme",
        "spatstat.data",
        "spatstat.geom",
        "spatstat.random",
        "spatstat.sparse",
        "spatstat.utils",
        "stats",
        "utils"
      ],
      "Hash": "b590c5d278d0606d53278afac666ad60"
    },
    "spatstat.geom": {
      "Package": "spatstat.geom",
      "Version": "3.2-9",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "deldir",
        "grDevices",
        "graphics",
        "methods",
        "polyclip",
        "spatstat.data",
        "spatstat.utils",
        "stats",
        "utils"
      ],
      "Hash": "96b9f23da42d16660aa6d136ad99cf5f"
    },
    "spatstat.random": {
      "Package": "spatstat.random",
      "Version": "3.2-3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "methods",
        "spatstat.data",
        "spatstat.geom",
        "spatstat.utils",
        "stats",
        "utils"
      ],
      "Hash": "01aff260c49550e820a47d97e566af6a"
    },
    "spatstat.sparse": {
      "Package": "spatstat.sparse",
      "Version": "3.0-3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "R",
        "abind",
        "methods",
        "spatstat.utils",
        "stats",
        "tensor",
        "utils"
      ],
      "Hash": "1daaecefd754bb259a5ad5ce95a2cdcc"
    },
    "spatstat.utils": {
      "Package": "spatstat.utils",
      "Version": "3.0-4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "graphics",
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "81d929f43f8532c1f8180a105449d414"
    },
    "statmod": {
      "Package": "statmod",
      "Version": "1.5.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "graphics",
        "stats"
      ],
      "Hash": "26e158d12052c279bdd4ba858b80fb1f"
    },
    "stringfish": {
      "Package": "stringfish",
      "Version": "0.16.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "Rcpp",
        "RcppParallel"
      ],
      "Hash": "b7eb79470319ae71d4b5ed9cd7bf7294"
    },
    "stringi": {
      "Package": "stringi",
      "Version": "1.8.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "stats",
        "tools",
        "utils"
      ],
      "Hash": "39e1144fd75428983dc3f63aa53dfa91"
    },
    "stringr": {
      "Package": "stringr",
      "Version": "1.5.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "cli",
        "glue",
        "lifecycle",
        "magrittr",
        "rlang",
        "stringi",
        "vctrs"
      ],
      "Hash": "960e2ae9e09656611e0b8214ad543207"
    },
    "survival": {
      "Package": "survival",
      "Version": "3.6-4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "R",
        "graphics",
        "methods",
        "splines",
        "stats",
        "utils"
      ],
      "Hash": "e6e3071f471513e4b85f98ca041303c7"
    },
    "sva": {
      "Package": "sva",
      "Version": "3.52.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "BiocParallel",
        "R",
        "edgeR",
        "genefilter",
        "graphics",
        "limma",
        "matrixStats",
        "mgcv",
        "stats",
        "utils"
      ],
      "Hash": "feabd0ba05b66ab807da4e66bbe69ea0"
    },
    "symphony": {
      "Package": "symphony",
      "Version": "0.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "R",
        "RANN",
        "RColorBrewer",
        "Rcpp",
        "RcppArmadillo",
        "class",
        "data.table",
        "dplyr",
        "ggplot2",
        "harmony",
        "irlba",
        "magrittr",
        "methods",
        "purrr",
        "rlang",
        "stats",
        "tibble",
        "tidyr",
        "utils",
        "uwot"
      ],
      "Hash": "505f66fcd108e78c348da1d8661fc70f"
    },
    "sys": {
      "Package": "sys",
      "Version": "3.4.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "3a1be13d68d47a8cd0bfd74739ca1555"
    },
    "systemfonts": {
      "Package": "systemfonts",
      "Version": "1.1.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "cpp11",
        "lifecycle"
      ],
      "Hash": "213b6b8ed5afbf934843e6c3b090d418"
    },
    "tensor": {
      "Package": "tensor",
      "Version": "1.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "25cfab6cf405c15bccf7e69ec39df090"
    },
    "testthat": {
      "Package": "testthat",
      "Version": "3.2.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "R6",
        "brio",
        "callr",
        "cli",
        "desc",
        "digest",
        "evaluate",
        "jsonlite",
        "lifecycle",
        "magrittr",
        "methods",
        "pkgload",
        "praise",
        "processx",
        "ps",
        "rlang",
        "utils",
        "waldo",
        "withr"
      ],
      "Hash": "3f6e7e5e2220856ff865e4834766bf2b"
    },
    "textshaping": {
      "Package": "textshaping",
      "Version": "0.3.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "cpp11",
        "systemfonts"
      ],
      "Hash": "997aac9ad649e0ef3b97f96cddd5622b"
    },
    "tibble": {
      "Package": "tibble",
      "Version": "3.2.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "fansi",
        "lifecycle",
        "magrittr",
        "methods",
        "pillar",
        "pkgconfig",
        "rlang",
        "utils",
        "vctrs"
      ],
      "Hash": "a84e2cc86d07289b3b6f5069df7a004c"
    },
    "tidyr": {
      "Package": "tidyr",
      "Version": "1.3.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "cli",
        "cpp11",
        "dplyr",
        "glue",
        "lifecycle",
        "magrittr",
        "purrr",
        "rlang",
        "stringr",
        "tibble",
        "tidyselect",
        "utils",
        "vctrs"
      ],
      "Hash": "915fb7ce036c22a6a33b5a8adb712eb1"
    },
    "tidyselect": {
      "Package": "tidyselect",
      "Version": "1.2.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "cli",
        "glue",
        "lifecycle",
        "rlang",
        "vctrs",
        "withr"
      ],
      "Hash": "829f27b9c4919c16b593794a6344d6c0"
    },
    "tinytex": {
      "Package": "tinytex",
      "Version": "0.51",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "xfun"
      ],
      "Hash": "d44e2fcd2e4e076f0aac540208559d1d"
    },
    "tximport": {
      "Package": "tximport",
      "Version": "1.32.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Requirements": [
        "methods",
        "stats",
        "utils"
      ],
      "Hash": "de83dfc887cf6205591b70500c987e43"
    },
    "tzdb": {
      "Package": "tzdb",
      "Version": "0.4.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "cpp11"
      ],
      "Hash": "f561504ec2897f4d46f0c7657e488ae1"
    },
    "utf8": {
      "Package": "utf8",
      "Version": "1.2.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "62b65c52671e6665f803ff02954446e9"
    },
    "uwot": {
      "Package": "uwot",
      "Version": "0.2.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "FNN",
        "Matrix",
        "RSpectra",
        "Rcpp",
        "RcppAnnoy",
        "RcppProgress",
        "dqrng",
        "irlba",
        "methods"
      ],
      "Hash": "f693a0ca6d34b02eb432326388021805"
    },
    "varhandle": {
      "Package": "varhandle",
      "Version": "2.0.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "graphics",
        "utils"
      ],
      "Hash": "e4f5f4e4bd5925183a7014afdc3e9848"
    },
    "vctrs": {
      "Package": "vctrs",
      "Version": "0.6.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "cli",
        "glue",
        "lifecycle",
        "rlang"
      ],
      "Hash": "c03fa420630029418f7e6da3667aac4a"
    },
    "vipor": {
      "Package": "vipor",
      "Version": "0.4.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "graphics",
        "stats"
      ],
      "Hash": "86493c62c14eb78140f1725003958a77"
    },
    "viridis": {
      "Package": "viridis",
      "Version": "0.6.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "ggplot2",
        "gridExtra",
        "viridisLite"
      ],
      "Hash": "acd96d9fa70adeea4a5a1150609b9745"
    },
    "viridisLite": {
      "Package": "viridisLite",
      "Version": "0.4.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R"
      ],
      "Hash": "c826c7c4241b6fc89ff55aaea3fa7491"
    },
    "vroom": {
      "Package": "vroom",
      "Version": "1.6.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "bit64",
        "cli",
        "cpp11",
        "crayon",
        "glue",
        "hms",
        "lifecycle",
        "methods",
        "progress",
        "rlang",
        "stats",
        "tibble",
        "tidyselect",
        "tzdb",
        "vctrs",
        "withr"
      ],
      "Hash": "390f9315bc0025be03012054103d227c"
    },
    "waldo": {
      "Package": "waldo",
      "Version": "0.5.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "cli",
        "diffobj",
        "fansi",
        "glue",
        "methods",
        "rematch2",
        "rlang",
        "tibble"
      ],
      "Hash": "c7d3fd6d29ab077cbac8f0e2751449e6"
    },
    "websocket": {
      "Package": "websocket",
      "Version": "1.4.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "AsioHeaders",
        "R6",
        "cpp11",
        "later"
      ],
      "Hash": "76e0d400757e318cca33def29ccebbc2"
    },
    "withr": {
      "Package": "withr",
      "Version": "3.0.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "graphics"
      ],
      "Hash": "d31b6c62c10dcf11ec530ca6b0dd5d35"
    },
    "xfun": {
      "Package": "xfun",
      "Version": "0.44",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "grDevices",
        "stats",
        "tools"
      ],
      "Hash": "317a0538d32f4a009658bcedb7923f4b"
    },
    "xgboost": {
      "Package": "xgboost",
      "Version": "1.7.7.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "Matrix",
        "R",
        "data.table",
        "jsonlite",
        "methods"
      ],
      "Hash": "6303e61eac62aef7bd2b396ef7e24386"
    },
    "xml2": {
      "Package": "xml2",
      "Version": "1.3.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "cli",
        "methods",
        "rlang"
      ],
      "Hash": "1d0336142f4cd25d8d23cd3ba7a8fb61"
    },
    "xopen": {
      "Package": "xopen",
      "Version": "1.0.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "processx"
      ],
      "Hash": "423df1e86d5533fcb73c6b02b4923b49"
    },
    "xtable": {
      "Package": "xtable",
      "Version": "1.8-4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "stats",
        "utils"
      ],
      "Hash": "b8acdf8af494d9ec19ccb2481a9b11c2"
    },
    "yaml": {
      "Package": "yaml",
      "Version": "2.3.8",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "29240487a071f535f5e5d5a323b7afbd"
    },
    "zlibbioc": {
      "Package": "zlibbioc",
      "Version": "1.50.0",
      "Source": "Bioconductor",
      "Repository": "Bioconductor 3.19",
      "Hash": "3db02e3c460e1c852365df117a2b441b"
    },
    "zoo": {
      "Package": "zoo",
      "Version": "1.8-12",
      "Source": "Repository",
      "Repository": "CRAN",
      "Requirements": [
        "R",
        "grDevices",
        "graphics",
        "lattice",
        "stats",
        "utils"
      ],
      "Hash": "5c715954112b45499fb1dadc6ee6ee3e"
    }
  }
}
