biogps <- readRDS('data-raw/single-cell/biogps/biogps.rds')
cell_info <- readRDS('data-raw/cell_info/cell_info.rds')
# gslist.kegg <- readRDS('data-raw/padog/gslist.rds')
# gs.names.kegg <- readRDS('data-raw/padog/gs.names.rds')
# gslist.go <- readRDS('data-raw/padog/gslist.go.rds')
# gs.names.go <- readRDS('data-raw/padog/gs.names.go.rds')
genes <- readRDS('data-raw/genes/genes.rds')
pert_names <- readRDS('data-raw/drug_gene_queries/pert_names.rds')

usethis::use_data(biogps, cell_info, genes, pert_names, internal = TRUE, overwrite = TRUE)
