library(data.table)

# from http://uswest.ensembl.org/info/genome/stable_ids/prefixes.html

ensmap <- fread("Prefix	Species name
ENSLCO	Lepidothrix coronata (Blue-crowned manakin)
ENSCHI	Capra hircus (Goat)
MGP_129S1SvImJ_	Mus musculus (Mouse 129S1/SvImJ)
ENSETE	Echinops telfairi (Lesser hedgehog tenrec)
ENSCAT	Cercocebus atys (Sooty mangabey)
ENSSTO	Ictidomys tridecemlineatus (Squirrel)
ENSNBR	Neolamprologus brichardi (Lyretail cichlid)
ENSLCR	Larimichthys crocea (Large yellow croaker)
ENSOSU	Otus sunia (Oriental scops-owl)
ENSSSC	Sus scrofa (Pig USMARC)
ENSFHE	Fundulus heteroclitus (Mummichog)
ENSNGA	Nannospalax galili (Upper Galilee mountains blind mole rat)
ENSGFO	Geospiza fortis (Medium ground-finch)
ENSHHU	Hucho hucho (Huchen)
ENSSAU	Sparus aurata (Gilthead seabream)
ENSCCR	Cyprinus carpio (Common carp hebao red)
ENSJJA	Jaculus jaculus (Lesser Egyptian jerboa)
ENSTGE	Theropithecus gelada (Gelada)
ENSMVI	Manacus vitellinus (Golden-collared manakin)
ENSCMU	Corvus moneduloides (New Caledonian crow)
ENSCGO	Cottoperca gobio (Channel bull blenny)
ENSARW	Apteryx rowi (Okarito brown kiwi)
MGP_C57BL6NJ_	Mus musculus (Mouse C57BL/6NJ)
ENSLLT	Laticauda laticaudata (Blue-ringed sea krait)
ENSMNE	Macaca nemestrina (Pig-tailed macaque)
ENSCSA	Chlorocebus sabaeus (Vervet-AGM)
ENSDLE	Delphinapterus leucas (Beluga whale)
ENSOAR	Ovis aries (Sheep)
ENSPNA	Pygocentrus nattereri (Red-bellied piranha)
ENSCSAV	Ciona savignyi
ENSNLE	Nomascus leucogenys (Gibbon)
ENSPNY	Pundamilia nyererei (Makobe Island cichlid)
ENSCCA	Cebus capucinus imitator (Capuchin)
ENSPVA	Pteropus vampyrus (Megabat)
ENSCHI	Capra hircus (Goat (black bengal))
ENSCUS	Catharus ustulatus (Swainson's thrush)
ENSLSD	Lonchura striata domestica (Bengalese finch)
ENSSSC	Sus scrofa (Pig - Hampshire)
ENSHBU	Haplochromis burtoni (Burton's mouthbrooder)
MGP_CAROLIEiJ_	Mus caroli (Ryukyu mouse)
ENSCAF	Canis lupus familiaris (Dog - Basenji)
ENSMZE	Maylandia zebra (Zebra mbuna)
ENSSVL	Sciurus vulgaris (Eurasian red squirrel)
ENSANA	Aotus nancymaae (Ma's night monkey)
ENSCHY	Cervus hanglu yarkandensis (Yarkand deer)
ENSDNV	Dromaius novaehollandiae (Emu)
ENSPFO	Poecilia formosa (Amazon molly)
ENSUAM	Ursus americanus (American black bear)
ENSSSC	Sus scrofa (Pig - Berkshire)
ENSCJP	Coturnix japonica (Japanese quail)
ENSNPE	Nothoprocta perdicaria (Chilean tinamou)
ENSSHB	Strigops habroptila (Kakapo)
ENSZAL	Zonotrichia albicollis (White-throated sparrow)
ENSMUN	Melopsittacus undulatus (Budgerigar)
ENSAHA	Apteryx haastii (Great spotted kiwi)
ENSSSC	Sus scrofa (Pig - Largewhite)
ENSBMU	Bos mutus (Wild yak)
ENSOAR	Ovis aries (Sheep (texel))
ENSZLM	Zosterops lateralis melanops (Silver-eye)
ENSELU	Esox lucius (Northern pike)
ENSPCE	Pelusios castaneus (West African mud turtle)
ENSCCR	Cyprinus carpio (Common carp huanghe)
ENSAOC	Amphiprion ocellaris (Clown anemonefish)
ENSPTR	Pan troglodytes (Chimpanzee)
ENSOKI	Oncorhynchus kisutch (Coho salmon)
ENSMFA	Macaca fascicularis (Crab-eating macaque)
ENSRBI	Rhinopithecus bieti (Black snub-nosed monkey)
ENSPTX	Pseudonaja textilis (Eastern brown snake)
ENSCSE	Cynoglossus semilaevis (Tongue sole)
ENSXCO	Xiphophorus couchianus (Monterrey platyfish)
ENSORL	Oryzias latipes (Japanese medaka HdrR)
ENSSHA	Sarcophilus harrisii (Tasmanian devil)
ENSACL	Astatotilapia calliptera (Eastern happy)
ENSCHA	Clupea harengus (Atlantic herring)
ENSSSC	Sus scrofa (Pig - Pietrain)
ENSBJA	Buteo japonicus (Eastern buzzard)
ENSPST	Pavo cristatus (Indian peafowl)
ENSEBU	Eptatretus burgeri (Hagfish)
MGP_SPRETEiJ_	Mus spretus (Algerian mouse)
ENSIPU	Ictalurus punctatus (Channel catfish)
ENSBGR	Bos grunniens (Domestic yak)
ENSEEE	Electrophorus electricus (Electric eel)
ENSCCN	Castor canadensis (American beaver)
ENSCGR	Cricetulus griseus (Chinese hamster PICR)
ENSAMX	Astyanax mexicanus (Mexican tetra)
ENSVPA	Vicugna pacos (Alpaca)
ENSCEL	Caenorhabditis elegans (Caenorhabditis elegans)
ENSNME	Numida meleagris (Helmeted guineafowl)
ENSEEU	Erinaceus europaeus (Hedgehog)
ENSMGA	Meleagris gallopavo (Turkey)
ENSPME	Poecilia mexicana (Shortfin molly)
ENSDCD	Denticeps clupeoides (Denticle herring)
ENSRRO	Rhinopithecus roxellana (Golden snub-nosed monkey)
ENSHGLM	Heterocephalus glaber (Naked mole-rat male)
ENSOSI	Oryzias sinensis (Chinese medaka)
ENSSSC	Sus scrofa (Pig)
ENSMAM	Mastacembelus armatus (Zig-zag eel)
ENSDNO	Dasypus novemcinctus (Armadillo)
ENSTGU	Taeniopygia guttata (Zebra finch)
ENSCVA	Cyprinodon variegatus (Sheepshead minnow)
ENSLAF	Loxodonta africana (Elephant)
ENSMMN	Monodon monoceros (Narwhal)
ENSTBE	Tupaia belangeri (Tree Shrew)
ENSUMA	Ursus maritimus (Polar bear)
ENSCHO	Choloepus hoffmanni (Sloth)
ENSXET	Xenopus tropicalis (Tropical clawed frog)
ENSPTE	Piliocolobus tephrosceles (Ugandan red Colobus)
ENSACI	Amphilophus citrinellus (Midas cichlid)
ENSMLU	Myotis lucifugus (Microbat)
ENSXMA	Xiphophorus maculatus (Platyfish)
ENSNSU	Notechis scutatus (Mainland tiger snake)
ENSOTS	Oncorhynchus tshawytscha (Chinook salmon)
ENSPSM	Prolemur simus (Greater bamboo lemur)
ENSCCR	Cyprinus carpio (Common carp german mirror)
ENSPRE	Poecilia reticulata (Guppy)
ENSTNI	Tetraodon nigroviridis (Tetraodon)
ENSSSC	Sus scrofa (Pig - Rongchang)
ENSCDR	Camelus dromedarius (Arabian camel)
ENSAPL	Anas platyrhynchos (Mallard)
ENSPCI	Phascolarctos cinereus (Koala)
ENSSLU	Sander lucioperca (Pike-perch)
ENSOME	Oryzias melastigma (Indian medaka)
ENSCGR	Cricetulus griseus (Chinese hamster CHOK1GS)
ENSGAL	Gallus gallus (Chicken)
ENSFTI	Falco tinnunculus (Common kestrel)
ENSAME	Ailuropoda melanoleuca (Giant panda)
ENSAZO	Anas zonorhyncha (Eastern spot-billed duck)
ENSPSN	Phocoena sinus (Vaquita)
ENSMIC	Microcebus murinus (Mouse Lemur)
ENSMOC	Microtus ochrogaster (Prairie vole)
ENSPMJ	Parus major (Great Tit)
ENSSBO	Saimiri boliviensis boliviensis (Bolivian squirrel monkey)
ENSPPR	Panthera pardus (Leopard)
ENSPLA	Poecilia latipinna (Sailfin molly)
ENSBMS	Balaenoptera musculus (Blue whale)
ENSACO	Amazona collaria (Yellow-billed parrot)
ENSPCA	Procavia capensis (Hyrax)
ENSGWI	Gouania willdenowi (Blunt-snouted clingfish)
ENSCLM	Cyclopterus lumpus (Lumpfish)
ENSPMA	Petromyzon marinus (Lamprey)
ENSCPR	Crocodylus porosus (Australian saltwater crocodile)
ENSAOW	Apteryx owenii (Little spotted kiwi)
ENSOGA	Otolemur garnettii (Bushbaby)
ENS	Homo sapiens (Human)
ENSCLA	Chinchilla lanigera (Long-tailed chinchilla)
ENSECR	Erpetoichthys calabaricus (Reedfish)
ENSCPV	Camarhynchus parvulus (Small tree finch)
ENSEGO	Erythrura gouldiae (Gouldian finch)
ENSPMR	Podarcis muralis (Common wall lizard)
ENSPKI	Paramormyrops kingsleyae (Paramormyrops kingsleyae)
ENSPPA	Pan paniscus (Bonobo)
ENSSMR	Salvator merianae (Argentine black and white tegu)
ENSSSC	Sus scrofa (Pig - Tibetan)
ENSHGLF	Heterocephalus glaber (Naked mole-rat female)
ENSPPY	Pongo abelii (Orangutan)
ENSOMY	Oncorhynchus mykiss (Rainbow trout)
ENSPAN	Papio anubis (Olive baboon)
ENSRFE	Rhinolophus ferrumequinum (Greater horseshoe bat)
ENSMOD	Monodelphis domestica (Opossum)
ENSCCR	Cyprinus carpio (Common carp)
ENSTMT	Terrapene carolina triunguis (Three-toed box turtle)
ENSTRU	Takifugu rubripes (Fugu)
ENSATE	Anabas testudineus (Climbing perch)
ENSBIX	Bos indicus x Bos taurus (Hybrid - Bos Taurus)
ENSAPO	Acanthochromis polyacanthus (Spiny chromis)
ENSABR	Anser brachyrhynchus (Pink-footed goose)
ENSMMU	Macaca mulatta (Macaque)
ENSSAN	Sinocyclocheilus anshuiensis (Blind barbel)
ENSMAU	Mesocricetus auratus (Golden Hamster)
ENSMAL	Monopterus albus (Swamp eel)
ENSCGR	Cricetulus griseus (Chinese hamster CriGri)
ENSCAB	Chelonoidis abingdonii (Abingdon island giant tortoise)
ENSKMA	Kryptolebias marmoratus (Mangrove rivulus)
ENSSSC	Sus scrofa (Pig - Jinhua)
ENSRNO	Rattus norvegicus (Rat)
ENSUTT	Ursus thibetanus thibetanus (Asiatic black bear)
ENSBBB	Bison bison bison (American bison)
MGP_DBA2J_	Mus musculus (Mouse DBA/2J)
ENSHCO	Hippocampus comes (Tiger tail seahorse)
ENSZCA	Zalophus californianus (California sea lion)
ENSSLD	Seriola lalandi dorsalis (Yellowtail amberjack)
MGP_CASTEiJ_	Mus musculus castaneus (Mouse CAST/EiJ)
ENSSPU	Sphenodon punctatus (Tuatara)
ENSNFU	Nothobranchius furzeri (Turquoise killifish)
ENSPCO	Propithecus coquereli (Coquerel's sifaka)
ENSCPI	Chrysolophus pictus (Golden pheasant)
ENSAPL	Anas platyrhynchos platyrhynchos (Duck)
ENSSGR	Sinocyclocheilus grahami (Golden-line barbel)
ENSSRH	Sinocyclocheilus rhinocerous (Horned golden-line barbel)
ENSMMM	Marmota marmota marmota (Alpine marmot)
ENSFAL	Ficedula albicollis (Collared flycatcher)
ENSSSC	Sus scrofa (Pig - Landrace)
ENSBSL	Betta splendens (Siamese fighting fish)
MGP_FVBNJ_	Mus musculus (Mouse FVB/NJ)
ENSENL	Echeneis naucrates (Live sharksucker)
ENSSFA	Salarias fasciatus (Jewelled blenny)
ENSGEV	Gopherus evgoodei (Goodes thornscrub tortoise)
ENSSSA	Salmo salar (Atlantic salmon)
ENSACC	Aquila chrysaetos chrysaetos (Golden eagle)
ENSACU	Athene cunicularia (Burrowing owl)
ENSSSC	Sus scrofa (Pig - Wuzhishan)
ENSOAB	Oreochromis aureus (Blue tilapia)
ENSONI	Oreochromis niloticus (Nile tilapia)
ENSTTR	Tursiops truncatus (Dolphin)
ENSCCE	Cyanistes caeruleus (Blue tit)
ENSACA	Anolis carolinensis (Green anole)
ENSCAF	Canis lupus dingo (Dingo)
ENSEAS	Equus asinus asinus (Donkey)
ENSCPI	Chrysemys picta bellii (Painted turtle)
ENSOJA	Oryzias javanicus (Javanese ricefish)
MGP_AKRJ_	Mus musculus (Mouse AKR/J)
ENSPEM	Peromyscus maniculatus bairdii (Northern American deer mouse)
MGP_PahariEiJ_	Mus pahari (Shrew mouse)
ENSMUS	Mus musculus (Mouse)
ENSVKK	Varanus komodoensis (Komodo dragon)
MGP_AJ_	Mus musculus (Mouse A/J)
ENSLAC	Latimeria chalumnae (Coelacanth)
ENSCIN	Ciona intestinalis
ENSOPR	Ochotona princeps (Pika)
ENSSTU	Salmo trutta (Brown trout)
ENSSDA	Spermophilus dauricus (Daurian ground squirrel)
ENSBIX	Bos indicus x Bos taurus (Hybrid - Bos Indicus)
ENSCHA	Scleropages formosus (Asian bonytongue)
ENSMUG	Meriones unguiculatus (Mongolian gerbil)
ENSPCL	Phasianus colchicus (Ring-necked pheasant)
ENSGAF	Gambusia affinis (Western mosquitofish)
ENSLOC	Lepisosteus oculatus (Spotted gar)
ENSACD	Anser cygnoides (Swan goose)
ENSPCT	Physeter catodon (Sperm whale)
MGP_PWKPhJ_	Mus musculus musculus (Mouse PWK/PhJ)
ENSMPU	Mustela putorius furo (Ferret)
ENSPTI	Panthera tigris altaica (Tiger)
ENSLBE	Labrus bergylta (Ballan wrasse)
ENSLCN	Lynx canadensis (Canada lynx)
ENSCMM	Cairina moschata domestica (Muscovy Duck (domestic type))
ENSCRF	Cyanoderma ruficeps (Rufous-capped babbler)
ENSCPG	Calidris pygmaea (Spoon-billed sandpiper)
MGP_NODShiLtJ_	Mus musculus (Mouse NOD/ShiLtJ)
ENSLLE	Leptobrachium leishanense (Leishan spiny toad)
ENSCAN	Colobus angolensis palliatus (Angola colobus)
ENSCJA	Callithrix jacchus (Marmoset)
ENSSCU	Struthio camelus australis (African ostrich)
ENSCAF	Canis lupus familiaris (Dog - Great Dane)
ENSSSC	Sus scrofa (Pig - Bamei)
ENSOAN	Ornithorhynchus anatinus (Platypus)
ENSMLE	Mandrillus leucophaeus (Drill)
ENSPMG	Periophthalmus magnuspinnatus (Periophthalmus magnuspinnatus)
ENSCAP	Cavia aperea (Brazilian guinea pig)
ENSTSY	Carlito syrichta (Tarsier)
ENSMMD	Myripristis murdjan (Pinecone soldierfish)
ENSCPU	Calidris pugnax (Ruff)
ENSDAR	Danio rerio (Zebrafish)
ENSGMO	Gadus morhua (Atlantic cod)
ENSSSU	Suricata suricatta (Meerkat)
ENSMEU	Notamacropus eugenii (Wallaby)
ENSPRN	Parambassis ranga (Indian glassy fish)
ENSORL	Oryzias latipes (Japanese medaka HSOK)
ENSANI	Accipiter nisus (Eurasian sparrowhawk)
ENSVVU	Vulpes vulpes (Red fox)
ENSSOC	Strix occidentalis caurina (Northern spotted owl)
ENSPVI	Pogona vitticeps (Central bearded dragon)
ENSAPE	Amphiprion percula (Orange clownfish)
ENSVUR	Vombatus ursinus (Common wombat)
ENSSDU	Seriola dumerili (Greater amberjack)
ENSNML	Neogobius melanostomus (Round goby)
MGP_NZOHlLtJ_	Mus musculus (Mouse NZO/HlLtJ)
ENSODE	Octodon degus (Degu)
ENSGAG	Gopherus agassizii (Agassiz's desert tortoise)
ENSDOR	Dipodomys ordii (Kangaroo rat)
ENSGAC	Gasterosteus aculeatus (Stickleback)
MGP_BALBcJ_	Mus musculus (Mouse BALB/cJ)
ENSFCA	Felis catus (Cat)
ENSMCS	Malurus cyaneus samueli (Superb fairywren)
ENSLCA	Lates calcarifer (Barramundi perch)
ENSCSR	Chelydra serpentina (Common snapping turtle)
ENSBOB	Bubo bubo (Eurasian eagle-owl)
ENSOCU	Oryctolagus cuniculus (Rabbit)
MGP_C3HHeJ_	Mus musculus (Mouse C3H/HeJ)
ENSPLO	Panthera leo (Lion)
ENSSPA	Stegastes partitus (Bicolor damselfish)
MGP_WSBEiJ_	Mus musculus domesticus (Mouse WSB/EiJ)
ENSNVI	Neovison vison (American mink)
ENSBTA	Bos taurus (Cow)
ENSCPO	Cavia porcellus (Guinea Pig)
MGP_CBAJ_	Mus musculus (Mouse CBA/J)
ENSMMO	Mola mola (Ocean sunfish)
ENSCMI	Callorhinchus milii (Elephant shark)
ENSJHY	Junco hyemalis (Dark-eyed junco)
ENSNNA	Naja naja (Indian cobra)
ENSPSI	Pelodiscus sinensis (Chinese softshell turtle)
MGP_LPJ_	Mus musculus (Mouse LP/J)
ENSECA	Equus caballus (Horse)
ENSCAF	Canis lupus familiaris (Dog)
ENSSOR	Sphaeramia orbicularis (Orbiculate cardinalfish)
ENSCWA	Catagonus wagneri (Chacoan peccary)
ENSORL	Oryzias latipes (Japanese medaka HNI)
ENSFDA	Fukomys damarensis (Damara mole rat)
ENSMSI	Mus spicilegus (Steppe mouse)
ENSMMS	Moschus moschiferus (Siberian musk deer)
ENSSSC	Sus scrofa (Pig - Meishan)
ENSUPA	Urocitellus parryii (Arctic ground squirrel)
ENSSAR	Sorex araneus (Shrew)
ENSGGO	Gorilla gorilla gorilla (Gorilla)
ENSAMX	Astyanax mexicanus (Pachon cavefish)
ENSSCA	Serinus canaria (Common canary)
ENSCAR	Carassius auratus (Goldfish)
ENSDLA	Dicentrarchus labrax (European seabass)
ENSSMA	Scophthalmus maximus (Turbot)")

utils::head(ensmap)
ensmap <- ensmap[!duplicated(ensmap$Prefix), ]
ensmap <- data.frame(row.names = ensmap$Prefix, species = gsub(' \\(.+?\\)|\\)', '', ensmap$`Species name`))
saveRDS(ensmap, 'data-raw/ensmap/ensmap.rds')
