name: ci
on:
  pull_request:
    types: [closed, opened, synchronize, reopened]
    branches:
      - master

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  DOCKERHUB_REPO: alexvpickering/dseqr

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          target: testing
          load: true
          cache-from: type=registry,ref=${{ env.DOCKERHUB_REPO }}:buildcache
          tags: ${{ env.DOCKERHUB_REPO }}:testing

      - name: Test
        run: |
          docker run --rm ${{ env.DOCKERHUB_REPO }}:testing

      - name: Build and push
        uses: docker/build-push-action@v2
        if: github.event.pull_request.merged == true
        with:
          context: .
          target: production
          push: true
          tags: ${{ env.DOCKERHUB_REPO }}:latest

      # push cache that includes production and testing
      - name: Build and push
        uses: docker/build-push-action@v2
        if: github.event.pull_request.merged == true
        with:
          context: .
          cache-to: type=registry,ref=${{ env.DOCKERHUB_REPO }}:buildcache,mode=max

